# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-13 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_skillbaserate_defaultrate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillbaserate',
            unique_together=set([]),
        ),
    ]
