# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-22 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_delete_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skillbaserate',
            unique_together=set([('skill', 'hourly_rate')]),
        ),
    ]
