# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_rate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillbaserate',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rate_defaults', to='skills.Skill', verbose_name='Skill'),
        ),
    ]
