# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_tag_confidential'),
        ('skills', '0009_set_skill_default_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_tags', to='skills.Skill', verbose_name='Skill')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_tags', to='core.Tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Skill Tag',
                'verbose_name_plural': 'Skill Tags',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='tags',
            field=models.ManyToManyField(related_name='skills', through='skills.SkillTag', to='core.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltag',
            unique_together=set([('tag', 'skill')]),
        ),
    ]
