# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_changed_company_contact_rels'),
        ('pricing', '0009_auto_20180625_1759'),
        ('skills', '0010_added_skill_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=127, verbose_name='Skill Name')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.Industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name_plural': 'Skills',
                'verbose_name': 'Skill',
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='skills.SkillName', verbose_name='Skill Name'),
        ),
    ]
