# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-30 09:22
from __future__ import unicode_literals

from django.db import migrations

from r3sourcer.apps.core.utils.companies import get_site_master_company


def migrate_skill_name(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")
    SkillName = apps.get_model("skills", "SkillName")
    Industry = apps.get_model("pricing", "Industry")
    Company = apps.get_model("core", "Company")

    if Skill.objects.all().exists():
        industry, _ = Industry.objects.get_or_create(type='Construction Industry')
        company = get_site_master_company()
        company = Company.objects.get(id=company.pk)

    for skill in Skill.objects.all():
        name, _ = SkillName.objects.get_or_create(name=skill.name, industry=industry)
        skill.skill_name = name
        skill.company = company
        skill.save(update_fields=['skill_name', 'company'])


def revert_skill_name(apps, schema_editor):
    Skill = apps.get_model("skills", "Skill")

    for skill in Skill.objects.all():
        skill.name = skill.skill_name.name
        skill.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_skill_name_model'),
    ]

    operations = [
        migrations.RunPython(migrate_skill_name, revert_skill_name),
    ]
