# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_move_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name'
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skills.SkillName', verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Company', verbose_name='Company'),
        ),
    ]
