# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-04 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0015_changed_skill_name_plural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='skills.SkillName', verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviation, for use by staff reports and dashboards', max_length=15, null=True, verbose_name='Short Name'),
        ),
    ]
