# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0018_auto_20191212_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.Company', verbose_name='Company'),
        ),
    ]
