# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0019_auto_20200515_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillname',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_names', to='pricing.Industry', verbose_name='Industry'),
        ),
    ]
