# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_replace_forms_bank_account'),
        ('pricing', '0020_auto_20191212_1443'),
        ('skills', '0020_auto_20200611_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNameLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127, verbose_name='Skill Name')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_names', to='core.Language', verbose_name='Skill name language')),
            ],
            options={
                'verbose_name': 'Skill Name Language',
                'verbose_name_plural': 'Skill Name Languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='skillname',
            unique_together=set([('name', 'industry')]),
        ),
        migrations.AddField(
            model_name='skillnamelanguage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_names', to='skills.SkillName', verbose_name='Skill Name'),
        ),
        migrations.AlterUniqueTogether(
            name='skillnamelanguage',
            unique_together=set([('name', 'language')]),
        ),
    ]
