# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0021_auto_20200712_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillnamelanguage',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='skills.SkillName', verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='skillnamelanguage',
            name='value',
            field=models.CharField(max_length=127, verbose_name='Skill Name transalation'),
        ),
    ]
