# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import r3sourcer.apps.core.mixins
import uuid


class Migration(migrations.Migration):

    def move_rates_to_skillraterange(apps, schema_editor):
        Skill = apps.get_model("skills", "Skill")
        SkillRateRange = apps.get_model("skills", "SkillRateRange")
        UnitOfMeasurement = apps.get_model("core", "UnitOfMeasurement")
        default_uom = UnitOfMeasurement.objects.get(default=True)

        for skill in Skill.objects.all():
            if skill.default_rate and skill.price_list_default_rate:
                SkillRateRange.objects.create(skill=skill,
                                            uom=default_uom,
                                            upper_rate_limit=skill.upper_rate_limit,
                                            lower_rate_limit=skill.lower_rate_limit,
                                            default_rate=skill.default_rate,
                                            price_list_upper_rate_limit=skill.price_list_upper_rate_limit,
                                            price_list_lower_rate_limit=skill.price_list_lower_rate_limit,
                                            price_list_default_rate=skill.price_list_default_rate)

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('skills', '0022_auto_20200712_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRateRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('upper_rate_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('lower_rate_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('price_list_upper_rate_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('price_list_lower_rate_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('price_list_default_rate', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'verbose_name': 'Skill Rate Range',
                'verbose_name_plural': 'Skill Rate Ranges',
            },
            bases=(r3sourcer.apps.core.mixins.MYOBMixin, models.Model),
        ),
        migrations.AddField(
            model_name='skillraterange',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rate_ranges', to='skills.Skill', verbose_name='Skill'),
        ),
        migrations.AddField(
            model_name='skillraterange',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_rate_ranges', to='core.UnitOfMeasurement', verbose_name='Unit of measurement'),
        ),
        migrations.RunPython(move_rates_to_skillraterange),
    ]
