# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-23 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('skills', '0023_skill_rate_ranges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='default_rate',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='lower_rate_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='price_list_default_rate',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='price_list_lower_rate_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='price_list_upper_rate_limit',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='upper_rate_limit',
        ),
        migrations.AlterUniqueTogether(
            name='skillraterange',
            unique_together=set([('skill', 'uom')]),
        ),
    ]
