# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('skills', '0025_worktype_worktypelanguage'),
    ]

    def set_default_uom(apps, schema_editor):
        UnitOfMeasurement = apps.get_model("core", "UnitOfMeasurement")
        WorkType = apps.get_model("skills", "WorkType")
        default_uom = UnitOfMeasurement.objects.get(default=True)
        WorkType.objects.all().update(uom=default_uom)

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Skill activity', 'verbose_name_plural': 'Skill activities'},
        ),
        migrations.AddField(
            model_name='worktype',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_rates', to='core.UnitOfMeasurement', verbose_name='Unit of measurement'),
        ),
        migrations.RunPython(set_default_uom),
        migrations.AlterField(
            model_name='worktype',
            name='uom',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_rates', to='core.UnitOfMeasurement', verbose_name='Unit of measurement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=127, verbose_name='Skill activity name'),
        ),
        migrations.AlterUniqueTogether(
            name='skillraterange',
            unique_together=set([('skill', 'worktype')]),
        ),
        migrations.RemoveField(
            model_name='skillraterange',
            name='uom',
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together=set([('skill_name', 'uom', 'name')]),
        ),
    ]
