# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-05 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    def set_worktype_to_hourly_work(apps, schema_editor):
        SkillRateRange = apps.get_model("skills", "SkillRateRange")

        for skillraterange in SkillRateRange.objects.all():
            if skillraterange.worktype == None:
                skillraterange.worktype = skillraterange.skill.name.work_types.filter(name='Hourly work').first()
                skillraterange.save()


    dependencies = [
        ('skills', '0028_auto_20210324_1434'),
    ]

    operations = [
        migrations.RunPython(set_worktype_to_hourly_work),
        migrations.AlterField(
            model_name='skillraterange',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rate_ranges', to='skills.WorkType', verbose_name='WorkType'),
        ),
    ]
