# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-12 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_make_company_contact_relation_unique'),
        ('skills', '0029_auto_20210405_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='skills.Skill', verbose_name='Skill'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('name', 'company')]),
        ),
    ]
