# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-28 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0030_auto_20210412_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktypelanguage',
            options={'verbose_name': 'Skill Activity Translation', 'verbose_name_plural': 'Skill Activity Transalations'},
        ),
    ]
