# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0031_auto_20210428_0505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktypelanguage',
            options={'verbose_name': 'Skill Activity Transalation', 'verbose_name_plural': 'Skill Activity Transalations'},
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tags', to='skills.Skill', verbose_name='Skill'),
        ),
        migrations.AlterField(
            model_name='skilltag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tags', to='core.Tag', verbose_name='Tag'),
        ),
    ]
