# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0032_auto_20210520_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillnamelanguage',
            name='value',
            field=models.CharField(max_length=127, verbose_name='Skill Name translation'),
        ),
    ]
