# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('test_name', models.CharField(max_length=255, verbose_name='Test Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(verbose_name='Valid Until')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Acceptance Test',
                'verbose_name_plural': 'Acceptance Tests',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTestAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
                ('order', models.SmallIntegerField(verbose_name='Order')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
            ],
            options={
                'verbose_name': 'Acceptance Test Answer',
                'verbose_name_plural': 'Acceptance Test Answers',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('acceptance_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_test_questions', to='acceptance_tests.AcceptanceTest', verbose_name='Acceptance Test')),
            ],
            options={
                'verbose_name': 'Acceptance Test Question',
                'verbose_name_plural': 'Acceptance Test Questions',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTestSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('acceptance_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_skills', to='acceptance_tests.AcceptanceTest', verbose_name='Acceptance Test')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_skills', to='skills.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Acceptance Test Skill',
                'verbose_name_plural': 'Acceptance Tests and Skills',
            },
        ),
        migrations.AddField(
            model_name='acceptancetestanswer',
            name='acceptance_test_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_test_answers', to='acceptance_tests.AcceptanceTestQuestion', verbose_name='Acceptance Test Question'),
        ),
    ]
