# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_added_skill_tags'),
        ('core', '0056_workflownode_path_readonly'),
        ('acceptance_tests', '0001_initial'),
        ('pricing', '0009_auto_20180625_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetestanswer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Default score for Options type', verbose_name='Score'),
        ),
        migrations.AddField(
            model_name='acceptancetestquestion',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Options'), (1, 'Text'), (2, 'Yes/No')], default=0, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='AcceptanceTestIndustry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Acceptance Test Industry',
                'verbose_name_plural': 'Acceptance Tests and Industries',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTestTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Acceptance Test Tag',
                'verbose_name_plural': 'Acceptance Tests and Tags',
            },
        ),
        migrations.CreateModel(
            name='AcceptanceTestWorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Acceptance Test Workflow Node',
                'verbose_name_plural': 'Acceptance Tests and Workflow Nodes',
            },
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='skills',
            field=models.ManyToManyField(related_name='acceptance_tests', through='acceptance_tests.AcceptanceTestSkill', to='skills.Skill', verbose_name='Related Skills'),
        ),
        migrations.AddField(
            model_name='acceptancetestquestion',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acceptancetestworkflownode',
            name='acceptance_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_workflow_nodes', to='acceptance_tests.AcceptanceTest', verbose_name='Acceptance Test'),
        ),
        migrations.AddField(
            model_name='acceptancetestworkflownode',
            name='workflow_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_workflow_nodes', to='core.WorkflowNode', verbose_name='Workflow Node'),
        ),
        migrations.AddField(
            model_name='acceptancetesttag',
            name='acceptance_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_tags', to='acceptance_tests.AcceptanceTest', verbose_name='Acceptance Test'),
        ),
        migrations.AddField(
            model_name='acceptancetesttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_tags', to='core.Tag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='acceptancetestindustry',
            name='acceptance_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_industries', to='acceptance_tests.AcceptanceTest', verbose_name='Acceptance Test'),
        ),
        migrations.AddField(
            model_name='acceptancetestindustry',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tests_industries', to='pricing.Industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='industries',
            field=models.ManyToManyField(related_name='acceptance_tests', through='acceptance_tests.AcceptanceTestIndustry', to='pricing.Industry', verbose_name='Related Industries'),
        ),
        migrations.AddField(
            model_name='acceptancetest',
            name='tags',
            field=models.ManyToManyField(related_name='acceptance_tests', through='acceptance_tests.AcceptanceTestTag', to='core.Tag', verbose_name='Related Tags'),
        ),
    ]
