# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-16 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0004_workflowobjectanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetestworkflownode',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='workflowobjectanswer',
            name='workflow_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_object_answers', to='core.WorkflowObject', verbose_name='Workflow Object'),
        ),
    ]
