# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0005_added_score_to_workflow_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowobjectanswer',
            name='exclude',
            field=models.BooleanField(default=False, verbose_name='Exclude from score'),
        ),
    ]
