# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-18 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0006_workflowobjectanswer_exclude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowobjectanswer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_object_answers', to='acceptance_tests.AcceptanceTestAnswer', verbose_name='Acceptance Test Answer'),
        ),
        migrations.AlterField(
            model_name='workflowobjectanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Text Answer'),
        ),
    ]
