# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-19 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0007_changed_workflow_object_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptancetestworkflownode',
            name='score',
        ),
    ]
