# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0013_acceptancetestpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptanceTestQuestionPicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('picture', easy_thumbnails.fields.ThumbnailerImageField(max_length=255, upload_to='acceptance_test_pictures')),
                ('acceptance_test_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='acceptance_tests.AcceptanceTestQuestion', verbose_name='Acceptance Test Question Picture')),
            ],
            options={
                'verbose_name': 'Acceptance Test Question Picture',
                'verbose_name_plural': 'Acceptance Tests Question Pictures',
            },
        ),
        migrations.RemoveField(
            model_name='acceptancetestpicture',
            name='acceptance_test',
        ),
        migrations.DeleteModel(
            name='AcceptanceTestPicture',
        ),
    ]
