# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-15 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0014_auto_20200731_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptancetestquestion',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Options'), (1, 'Text'), (2, 'Yes/No'), (3, 'Checkboxes')], default=0, verbose_name='Question Type'),
        ),
    ]
