# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance_tests', '0015_add_checkboxes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptancetestquestion',
            name='exclude_from_score',
            field=models.BooleanField(default=False, verbose_name='Exclude from score'),
        ),
    ]
