version: '2.0'
services:

#########
# REDIS #
#########

  redis:
    restart: always
    image: "redis:4-alpine"
    ports:
      - "6379:6379"
    networks:
      r3-network:
        ipv4_address: 192.168.100.2

##############
# CLICKHOUSE #
##############

  clickhouse:
    restart: always
    image: "yandex/clickhouse-server:18"
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-entrypoint.sh:/var/lib/clickhouse/clickhouse-entrypoint.sh
    entrypoint: /var/lib/clickhouse/clickhouse-entrypoint.sh
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      r3-network:
        ipv4_address: 192.168.100.3

############
# RABBITMQ #
############

  rabbitmq:
    restart: always
    image: "rabbitmq:3"
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      r3-network:
        ipv4_address: 192.168.100.4

############
# FRONTEND #
############

  nginx:
    restart: always
    image: "nginx:1"
    container_name: endlessproject_nginx_1
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env_defaults
      - ./.env
    volumes:
      - /home/ubuntu/endless_project/var/www/static/:/app/static/
      - /home/ubuntu/endless_project/var/www/media:/app/media/
      - /home/ubuntu/endless_project/webui-app/dist/:/app/webui/
      - /home/ubuntu/endless_project/conf/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      r3-network:
        ipv4_address: 192.168.100.5

###########
# BACKEND #
###########

  web:
    restart: always
    image: &img r3sourcer/r3:web-staging     # TODO set appropriate image name
    container_name: r3sourcer_web
    dns:
      - 8.8.8.8
    ports:
      - "8081:8081"
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    environment:
      - C_FORCE_ROOT=1
    env_file:
      - ./.env_defaults
      - ./.env
    volumes:
      -  /home/ubuntu/endless_project/var/www/:/app/var/www/
      - ./keys:/app/keys
    command: "./docker-entrypoint.sh"
    networks:
      r3-network:
        ipv4_address: 192.168.100.6

##########
# CELERY #
##########

  celery:
    image: *img
    container_name: r3sourcer_celery
    command: celery worker -n worker.celery -E -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler -Q celery,sms,hr
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    env_file:
      - ./.env_defaults
      - ./.env
    networks:
      r3-network:
        ipv4_address: 192.168.100.7

###############
# CELERY BEAT #
###############

  celery-beat:
    image: *img
    container_name: r3sourcer_celery_beat
    command: celery beat -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    env_file:
      - ./.env_defaults
      - ./.env
    networks:
      r3-network:
        ipv4_address: 192.168.100.8

networks:
  r3-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
