version: '2'
services:

#########
# REDIS #
#########

  redis:
    restart: always
    image: "redis:4-alpine"
    ports:
      - "6379:6379"

##############
# CLISCHOUSE #
##############

  clickhouse:
    restart: always
    image: "yandex/clickhouse-server:18"
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-entrypoint.sh:/var/lib/clickhouse/clickhouse-entrypoint.sh
    entrypoint: /var/lib/clickhouse/clickhouse-entrypoint.sh
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

############
# RABBITMQ #
############

  rabbitmq:
    restart: always
    image: "rabbitmq:3"
    ports:
      - 15672:15672
      - 5672:5672

############
# FRONTEND #
############

  nginx:
    restart: always
    image: "nginx:1"
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env_defaults
      - .env
    volumes:
      - ./var/www/static/:/app/static/
      - ./var/www/media:/app/media/
      - ./webui-app/dist/:/app/webui/
      - ./conf/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt

###########
# BACKEND #
###########

  web:
    restart: always
    image: &img r3sourcer/r3:web-staging
    container_name: r3sourcer_web
    dns:
      - 8.8.8.8
    ports:
      - "8081:8081"
    links:
      - redis
      - rabbitmq
      - clickhouse
    #   - postgres
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
      # - postgres
    environment:
      - C_FORCE_ROOT=1
    env_file:
      - .env_defaults
      - .env
    volumes:
      - /home/ubuntu/endless_project/var/www/:/app/var/www/
      - ./keys:/app/keys
    command: "./docker-entrypoint.sh"
##########
# CELERY #
##########

  celery:
    image: *img
    container_name: r3sourcer_celery
    command: celery worker -n worker.celery -E -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler -Q celery,sms,hr
    links:
      - redis
      - rabbitmq
      - clickhouse
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    env_file:
      - ./.env_defaults
      - ./.env

###############
# CELERY BEAT #
###############

  celery-beat:
    image: *img
    container_name: r3sourcer_celery_beat
    command: celery beat -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler
    links:
      - redis
      - rabbitmq
      - clickhouse
    depends_on:
      - redis
      - clickhouse
      - rabbitmq
    env_file:
      - ./.env_defaults
      - ./.env
