version: '2'
services:

  postgres:
    restart: always
    image: "postgres:9.6"
    env_file:
      - .env
  redis:
    restart: always
    image: "redis:alpine"

  clickhouse:
    image: yandex/clickhouse-server
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-entrypoint.sh:/var/lib/clickhouse/clickhouse-entrypoint.sh
    entrypoint: /var/lib/clickhouse/clickhouse-entrypoint.sh

  rabbitmq:
    restart: always
    image: "rabbitmq:3"

  nginx:
    restart: always
    image: "nginx"
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./var/www/static/:/app/static/
      - ./var/www/media:/app/media/
      - ./webui-app/dist/:/app/webui/
      - ./conf/docker/nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    restart: always
    build:
      context: .
      dockerfile: ./conf/docker/Dockerfile.dev
    ports:
      - "8081:8081"
    links:
      - postgres
      - redis
      - rabbitmq
      - clickhouse
    depends_on:
      - redis
      - postgres
      - clickhouse
      - rabbitmq
    environment:
      - C_FORCE_ROOT=1
    env_file:
      - .env
    volumes:
      - ./var/www/:/app/var/www/
      - ./r3sourcer/:/app/r3sourcer
      - ./helpers/:/app/helpers
      - ./conf:/app/conf
    command: "bin/app start"
