LOGGER_DB = 'Logger'
LOGGER_USER = None
LOGGER_PASSWORD = ''
LOGGER_HOST = 'localhost'
LOGGER_PORT = 8123


__all__ = [
    'LOGGER_DB', 'LOGGER_USER', 'LOGGER_PASSWORD', 'LOGGER_HOST', 'LOGGER_PORT'
]
