# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-03 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sms', 'SMS'), ('subscription', 'Subscription')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('stripe_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SMSBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('top_up_amount', models.IntegerField(default=100)),
                ('top_up_limit', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='subscription_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
