# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_payment_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS'), ('extra_workers', 'Extra Workers'), ('subscription', 'Subscription'), ('candidate', 'Candidate Profile')], max_length=255),
        ),
    ]
