# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_formbuilder_fields'),
        ('billing', '0007_auto_20180723_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, choices=[('sms', 'SMS'), ('extra_workers', 'Extra Workers'), ('subscription', 'Subscription')], max_length=255, null=True)),
                ('percent_off', models.IntegerField(blank=True, null=True)),
                ('amount_off', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('duration', models.CharField(choices=[('forever', 'Forever'), ('once', 'Once'), ('repeating', 'Repeating')], max_length=255)),
                ('duration_in_months', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.Company')),
            ],
        ),
    ]
