# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
