# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_discount_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsbalance',
            name='discount',
        ),
    ]
