# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-11 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_smsbalance_last_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsbalance',
            name='cost_of_segment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
