# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0013_smsbalance_auto_charge'),
    ]
    operations = [
        migrations.CreateModel(
        name='SubscriptionType',
        fields=[
            ('id',
             models.AutoField(auto_created=True, primary_key=True, serialize=False,
                              verbose_name='ID')),
            ('type', models.CharField(
                choices=[('annual', 'Annual'), ('monthly', 'Monthly')],
                max_length=255)),
            ('employess_total_num', models.PositiveIntegerField(blank=True, null=True)),
            ('max_employess_num', models.PositiveIntegerField(blank=True, null=True)),
            ('start_range', models.PositiveIntegerField(blank=True, null=True)),
            ('start_range_price_monthly', models.PositiveIntegerField(blank=True, null=True)),
            ('start_range_price_annual', models.PositiveIntegerField(blank=True, null=True)),
            ('step_change_val', models.PositiveIntegerField(blank=True, null=True)),
            ('heading', models.CharField(max_length=255, blank=True, null=True)),
            ('amount', models.PositiveIntegerField(blank=True, null=True)),
            ('amount_tag_line', models.CharField(max_length=255, blank=True, null=True)),
            ('amount_annual', models.CharField(max_length=255, blank=True, null=True)),
            ('table_text', models.CharField(max_length=255, blank=True, null=True)),
            ],
        ),
    ]