# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_subscription_types(apps, schema_editor):
    SubscriptionType = apps.get_model("billing", "SubscriptionType")
    t1 = SubscriptionType(type='annual', employess_total_num=10, max_employess_num=1005, start_range=5, step_change_val=7)
    t2 = SubscriptionType(type='monthly', employess_total_num=10, max_employess_num=1005, start_range=5, step_change_val=7)
    t1.save()
    t2.save()


def reverse_create_subscription_types(apps, schema_editor):
    SubscriptionType = apps.get_model("billing", "SubscriptionType")
    SubscriptionType.objects.all().delete()


def update_subscription_type(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    SubscriptionType = apps.get_model("billing", "SubscriptionType")
    annual_type = SubscriptionType.objects.get(type='annual')
    month_type = SubscriptionType.objects.get(type='monthly')

    Subscription.objects.filter(type='annual').update(subscription_type=annual_type)
    Subscription.objects.filter(type='monthly').update(subscription_type=month_type)


def reverse_update_subscription_type(apps, schema_editor):
    Subscription = apps.get_model("billing", "Subscription")
    SubscriptionType = apps.get_model("billing", "SubscriptionType")
    annual_type = SubscriptionType.objects.get(type='annual')
    month_type = SubscriptionType.objects.get(type='monthly')

    Subscription.objects.filter(subscription_type=annual_type).update(type='annual')
    Subscription.objects.filter(subscription_type=month_type).update(type='monthly')



class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='billing.SubscriptionType'),
        ),
        migrations.RunPython(create_subscription_types, reverse_code=reverse_create_subscription_types),
        migrations.RunPython(update_subscription_type, reverse_code=reverse_update_subscription_type),
    ]
