# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-24 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_add_subscription_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(blank=False, null=False, on_delete=models.deletion.SET_NULL, related_name='subscriptions', to='billing.SubscriptionType')
            )
    ]
