# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-03 08:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_created_country_stripe_account_model'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='stripecountryaccount',
        #     name='id',
        #     field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
    ]
