# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_change_defaults_for_datetime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecountryaccount',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Country', to_field='code2'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subscriptions', to='billing.SubscriptionType'),
        ),
    ]
