# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-19 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_auto_20210118_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsbalancelimits',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
