# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def load_sms_balance_limits_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "sms_balance_limits")

    def delete_sms_balance_limits(apps, schema_editor):
        SMSBalanceLimits = apps.get_model("billing", "SMSBalanceLimits")
        SMSBalanceLimits.objects.all().delete()

    dependencies = [
        ('billing', '0024_add_name_to_smsbalancelimits'),
    ]

    operations = [
        # migrations.RunPython(load_sms_balance_limits_from_fixture,
        #                      delete_sms_balance_limits),
    ]
