# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-27 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_add_low_balance_sent_to_smsbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsbalance',
            name='ran_out_balance_sent',
            field=models.BooleanField(default=False),
        ),
    ]
