# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-20 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0145_make_company_contact_relation_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPDFTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Template Name')),
                ('slug', models.SlugField()),
                ('html_template', models.TextField(blank=True, default='', verbose_name='HTML template')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_default_templates', to='core.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Default PDF Template',
                'verbose_name_plural': 'Default PDF Templates',
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(default='', max_length=256, verbose_name='Template Name')),
                ('slug', models.SlugField()),
                ('html_template', models.TextField(blank=True, default='', verbose_name='HTML template')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_templates', to='core.Company', verbose_name='Master company')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_templates', to='core.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'PDF Template',
                'verbose_name_plural': 'PDF Templates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='pdftemplate',
            unique_together=set([('company', 'name', 'slug', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='defaultpdftemplate',
            unique_together=set([('name', 'slug', 'language')]),
        ),
    ]
