# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def load_pdf_templates_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "pdf_templates", app_label="pdf_templates")

    def delete_pdf_templates(apps, schema_editor):
        DefaultPDFTemplate = apps.get_model("pdf_templates", "DefaultPDFTemplate")
        DefaultPDFTemplate.objects.all().delete()

    dependencies = [
        ('pdf_templates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_pdf_templates_from_fixture,
                             delete_pdf_templates),
    ]
