# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_templates', '0002_load_pdf_templates'),
    ]

    operations = [
    ]

    def load_pdf_templates_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "company_pdf_templates", app_label="pdf_templates")

    def delete_pdf_templates(apps, schema_editor):
        PDFTemplate = apps.get_model("pdf_templates", "PDFTemplate")
        PDFTemplate.objects.all().delete()

    operations = [
        migrations.RunPython(load_pdf_templates_from_fixture,
                             delete_pdf_templates),
    ]
