# Generated by Django 2.0.13 on 2023-03-07 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_templates', '0003_auto_20211112_1103'),
    ]

    def load_default_pdf_templates_from_fixture(apps, schema_editor):

        from django.core.management import call_command

        call_command("loaddata", "default_pdf_templates")


    def load_pdf_templates_from_fixture(apps, schema_editor):

        from django.core.management import call_command

        call_command("loaddata", "pdf_templates")


    operations = [

        migrations.RunPython(load_default_pdf_templates_from_fixture),

        migrations.RunPython(load_pdf_templates_from_fixture),

    ]
