# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 07:01
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Permission, ContentType


def create_permissions(apps, schema_editor):
    content_type, _ = ContentType.objects.get_or_create(model='global_permission',
                                                        app_label='endless_core')

    Permission.objects.create(name='Can view companies',
                              codename='company_endpoint_get',
                              content_type=content_type)
    Permission.objects.create(name='Can create companies',
                              codename='company_endpoint_post',
                              content_type=content_type)
    Permission.objects.create(name='Can change companies',
                              codename='company_endpoint_update',
                              content_type=content_type)
    Permission.objects.create(name='Can delete companies',
                              codename='company_endpoint_delete',
                              content_type=content_type)

    Permission.objects.create(name='Can view contacts',
                              codename='contact_endpoint_get',
                              content_type=content_type)
    Permission.objects.create(name='Can create contacts',
                              codename='contact_endpoint_post',
                              content_type=content_type)
    Permission.objects.create(name='Can change contacts',
                              codename='contact_endpoint_update',
                              content_type=content_type)
    Permission.objects.create(name='Can delete contacts',
                              codename='contact_endpoint_delete',
                              content_type=content_type)

    Permission.objects.create(name='Can view company contacts',
                              codename='company_contact_endpoint_get',
                              content_type=content_type)
    Permission.objects.create(name='Can create company contacts',
                              codename='company_contact_endpoint_post',
                              content_type=content_type)
    Permission.objects.create(name='Can change company contacts',
                              codename='company_contact_endpoint_update',
                              content_type=content_type)
    Permission.objects.create(name='Can delete company contacts',
                              codename='company_contact_endpoint_delete',
                              content_type=content_type)

    Permission.objects.create(name='Can view candidate contacts',
                              codename='candidate_contact_endpoint_get',
                              content_type=content_type)
    Permission.objects.create(name='Can create candidate contacts',
                              codename='candidate_contact_endpoint_post',
                              content_type=content_type)
    Permission.objects.create(name='Can change candidate contacts',
                              codename='candidate_contact_endpoint_update',
                              content_type=content_type)
    Permission.objects.create(name='Can delete candidate contacts',
                              codename='candidate_contact_endpoint_delete',
                              content_type=content_type)

    Permission.objects.create(name='Can view timesheets',
                              codename='timesheet_endpoint_get',
                              content_type=content_type)
    Permission.objects.create(name='Can create timesheets',
                              codename='timesheet_endpoint_post',
                              content_type=content_type)
    Permission.objects.create(name='Can change timesheets',
                              codename='timesheet_endpoint_update',
                              content_type=content_type)
    Permission.objects.create(name='Can delete timesheets',
                              codename='timesheet_endpoint_delete',
                              content_type=content_type)


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
    ]
