# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-08 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_settings', '0002_permission_objects_datamigration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('color_scheme', models.CharField(blank=True, max_length=32, null=True)),
                ('font', models.CharField(blank=True, max_length=32, null=True)),
                ('forwarding_number', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]