# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0003_myobcompanyfile_authenticated'),
        ('company_settings', '0004_add_accountset_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobaccount',
            name='company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myob.MYOBCompanyFile'),
        ),
    ]
