# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_company_company_settings'),
        ('myob', '0005_auto_20171207_0034'),
        ('company_settings', '0005_delete_account_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MYOBAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=63)),
                ('display_id', models.CharField(max_length=63)),
                ('classification', models.CharField(max_length=63)),
                ('type', models.CharField(max_length=63)),
                ('number', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('level', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_header', models.BooleanField()),
                ('uri', models.CharField(max_length=255)),
                ('row_version', models.CharField(max_length=255)),
                ('company_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='myob.MYOBCompanyFile')),
            ],
        ),
        migrations.CreateModel(
            name='MYOBSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_superannuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_superannuation', to='company_settings.MYOBAccount')),
                ('candidate_wages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_wages', to='company_settings.MYOBAccount')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myob_settings', to='core.Company')),
                ('company_client_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_gst', to='company_settings.MYOBAccount')),
                ('company_client_labour_hire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_labour_hire', to='company_settings.MYOBAccount')),
                ('subcontractor_contract_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_contract_work', to='company_settings.MYOBAccount')),
                ('subcontractor_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_gst', to='company_settings.MYOBAccount')),
            ],
        ),
        migrations.AddField(
            model_name='companysettings',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='core.Company'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
