# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0005_myobaccount_company_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobaccount',
            name='company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='myob.MYOBCompanyFile'),
        ),
    ]
