# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 18:31
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0006_auto_20171205_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobaccount',
            name='classification',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='display_id',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='is_header',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='row_version',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4(), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myobaccount',
            name='uri',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
