# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0006_add_myob_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobsettings',
            name='company_files_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myobsettings',
            name='payroll_accounts_last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
