# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_company_company_settings'),
        ('company_settings', '0007_auto_20171207_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MYOBSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_superannuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_superannuation', to='company_settings.MYOBAccount')),
                ('candidate_wages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_wages', to='company_settings.MYOBAccount')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myob_settings', to='core.Company')),
                ('company_client_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_gst', to='company_settings.MYOBAccount')),
                ('company_client_labour_hire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_labour_hire', to='company_settings.MYOBAccount')),
                ('subcontractor_contract_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_contract_work', to='company_settings.MYOBAccount')),
                ('subcontractor_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_gst', to='company_settings.MYOBAccount')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='candidate_superannuation',
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='candidate_wages',
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='company_client_gst',
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='company_client_labour_hire',
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='subcontractor_contract_work',
        ),
        migrations.RemoveField(
            model_name='accountset',
            name='subcontractor_gst',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='core.Company'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='account_set',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='company_settings.MYOBSettings'),
        ),
        migrations.DeleteModel(
            name='AccountSet',
        ),
    ]
