# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-14 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_settings(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    CompanySettings = apps.get_model("company_settings", "CompanySettings")
    MYOBSettings = apps.get_model("company_settings", "MYOBSettings")

    companies = Company.objects.all()

    for company in companies:
        if not hasattr(company, 'company_settings'):
            CompanySettings.objects.create(company=company)

        if not hasattr(company, 'myob_settings'):
            MYOBSettings.objects.create(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_company_company_settings'),
        ('myob', '0005_update_companyfiletoken'),
        ('company_settings', '0008_remove_old_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('color_scheme', models.CharField(blank=True, max_length=32, null=True)),
                ('font', models.CharField(blank=True, max_length=32, null=True)),
                ('forwarding_number', models.CharField(blank=True, max_length=32, null=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_settings', to='core.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MYOBAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('uid', models.UUIDField(unique=True)),
                ('name', models.CharField(max_length=63)),
                ('display_id', models.CharField(max_length=63)),
                ('classification', models.CharField(max_length=63)),
                ('type', models.CharField(max_length=63)),
                ('number', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('level', models.IntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_header', models.BooleanField()),
                ('uri', models.CharField(max_length=255)),
                ('row_version', models.CharField(max_length=255)),
                ('company_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='myob.MYOBCompanyFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MYOBSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('payroll_accounts_last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('company_files_last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('candidate_superannuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_superannuation', to='company_settings.MYOBAccount')),
                ('candidate_wages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_wages', to='company_settings.MYOBAccount')),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myob_settings', to='core.Company')),
                ('company_client_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_gst', to='company_settings.MYOBAccount')),
                ('company_client_labour_hire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_labour_hire', to='company_settings.MYOBAccount')),
                ('subcontractor_contract_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_contract_work', to='company_settings.MYOBAccount')),
                ('subcontractor_gst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_gst', to='company_settings.MYOBAccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_settings, migrations.RunPython.noop)
    ]
