# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0006_myobsyncobject_company_file'),
        ('company_settings', '0010_auto_20180319_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Company settings', 'verbose_name_plural': 'Company settings'},
        ),
        migrations.AlterModelOptions(
            name='myobsettings',
            options={'verbose_name': 'MYOB settings', 'verbose_name_plural': 'MYOB settings'},
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='candidate_superannuation',
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='candidate_wages',
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='company_client_gst',
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='company_client_labour_hire',
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='subcontractor_contract_work',
        ),
        migrations.RemoveField(
            model_name='myobsettings',
            name='subcontractor_gst',
        ),
        migrations.AddField(
            model_name='myobsettings',
            name='invoice_activity_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_settings.MYOBAccount'),
        ),
        migrations.AddField(
            model_name='myobsettings',
            name='invoice_company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_company_files', to='myob.MYOBCompanyFile'),
        ),
        migrations.AddField(
            model_name='myobsettings',
            name='timesheet_company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_company_files', to='myob.MYOBCompanyFile'),
        ),
    ]
