# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-27 06:35
from __future__ import unicode_literals

from django.db import migrations
from r3sourcer.apps.core.models import Role


def grant_permission_to_clients(apps, schema_editor):
    User = apps.get_model("core", "User")
    GlobalPermission = apps.get_model("company_settings", "GlobalPermission")

    get_perm = GlobalPermission.objects.filter(codename='hr/timesheets_get').first()
    post_perm = GlobalPermission.objects.filter(codename='hr/timesheets_post').first()
    update_perm = GlobalPermission.objects.filter(codename='hr/timesheets_update').first()

    client_users = User.objects.filter(role__name=Role.ROLE_NAMES.client).exclude(
        user_permissions__in=[get_perm, post_perm, update_perm]
    )

    for user in client_users:
        user.user_permissions.add(get_perm)
        user.user_permissions.add(post_perm)
        user.user_permissions.add(update_perm)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_workflownode_initial'),
        ('company_settings', '0012_myob_settings_on_delete'),
    ]

    operations = [
        migrations.RunPython(grant_permission_to_clients, migrations.RunPython.noop),
    ]
