# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0014_companysettings_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
