# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0015_companysettings_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pre_shift_sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
