# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0016_companysettings_going_to_work_sms_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pre_shift_sms_delta',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
