# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0018_added_invoice_template_to_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='advance_state_saving',
            field=models.BooleanField(default=False),
        ),
    ]
