# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0021_auto_20191212_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='allow_job_creation',
            field=models.BooleanField(default=True),
        ),
    ]
