# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-18 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0023_companysettings_low_sms_balance_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='low_sms_balance_limit',
        ),
    ]
