# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-16 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0024_remove_companysettings_low_sms_balance_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAASCompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_sale_commission', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Candidate sale commission')),
            ],
            options={
                'verbose_name': 'SAAS company settings',
            },
        ),
    ]
