# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import r3sourcer.apps.core.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20171102_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('auth_token', models.CharField(max_length=32, unique=True, verbose_name='Auth Token')),
                ('loggedin_at', models.DateTimeField(blank=True, null=True, verbose_name='Logged in at')),
                ('redirect_to', models.CharField(default='/', max_length=63, verbose_name='Redirect Url')),
                ('type', models.SmallIntegerField(choices=[(0, 'SMS'), (1, 'E-mail')], default=0, verbose_name='Token type')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extranet_logins', to='core.Contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Token Login',
                'verbose_name_plural': 'Token Logins',
            },
            bases=(models.Model, r3sourcer.apps.core.mixins.GenerateAuthTokenMixin),
        ),
    ]
