# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 17:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('core', '0002_auto_20171102_1757'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceWorkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('allowance_description', models.TextField(blank=True, help_text='Examples: Travel Allowance, Waiting Hours, etc.', max_length=255, verbose_name='Allowance Description')),
            ],
            options={
                'verbose_name': 'Allowance Work Rule',
                'verbose_name_plural': 'Allowance Work Rules',
            },
        ),
        migrations.CreateModel(
            name='DynamicCoefficientRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Rule Priority')),
                ('rule_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'Dynamic Coefficient Rule',
                'verbose_name_plural': 'Dynamic Coefficient Rules',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.CharField(max_length=63, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
            },
        ),
        migrations.CreateModel(
            name='IndustryPriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('effective', models.BooleanField(default=False, verbose_name='Effective')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_price_lists', to='pricing.Industry', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Industry Price List',
                'verbose_name_plural': 'Industry Price Lists',
            },
        ),
        migrations.CreateModel(
            name='IndustryPriceListRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Hourly Rate')),
                ('industry_price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_price_list_rates', to='pricing.IndustryPriceList', verbose_name='Industry Price List')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='industry_price_list_rates', to='skills.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Industry Price List Rate',
                'verbose_name_plural': 'Industry Price List Rates',
            },
        ),
        migrations.CreateModel(
            name='IndustryRateCoefficient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('industry_price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.IndustryPriceList', verbose_name='Industry Price List')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimeWorkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('overtime_hours_from', models.DurationField(default=datetime.timedelta, help_text='Format: (HH:MM:SS)', verbose_name='Lower Overtime Hours Threshold')),
                ('overtime_hours_to', models.DurationField(default=datetime.timedelta, help_text='Format: (HH:MM:SS)', verbose_name='Upper Overtime Hours Threshold')),
            ],
            options={
                'verbose_name': 'Overtime Work Rule',
                'verbose_name_plural': 'Overtime Work Rules',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('valid_from', models.DateField(auto_now_add=True, verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('effective', models.BooleanField(default=False, verbose_name='Effective')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.CompanyContact', verbose_name='Approved By')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='core.Company', verbose_name='Company')),
                ('industry_price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='pricing.IndustryPriceList', verbose_name='Industry Price List')),
            ],
            options={
                'verbose_name': 'Price List',
                'verbose_name_plural': 'Price Lists',
            },
        ),
        migrations.CreateModel(
            name='PriceListRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Hourly Rate')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_rates', to='pricing.PriceList', verbose_name='Price List')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_rates', to='skills.Skill', verbose_name='Skill')),
            ],
            options={
                'verbose_name': 'Price List Rate',
                'verbose_name_plural': 'Price List Rates',
            },
        ),
        migrations.CreateModel(
            name='PriceListRateCoefficient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.PriceList', verbose_name='Price List')),
            ],
        ),
        migrations.CreateModel(
            name='RateCoefficient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=18, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.PositiveIntegerField(default=0, editable=False, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Rate Coefficient',
                'verbose_name_plural': 'Rate Coefficients',
            },
        ),
        migrations.CreateModel(
            name='RateCoefficientGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Rate Coefficient Group',
                'verbose_name_plural': 'Rate Coefficient Groups',
            },
        ),
        migrations.CreateModel(
            name='RateCoefficientModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Company'), (1, 'Candidate')], verbose_name='Type')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.00 = none', max_digits=4, verbose_name='Multiplier')),
                ('fixed_addition', models.DecimalField(decimal_places=2, default=0, help_text='adds after multiplying when set', max_digits=16, verbose_name='Fixed Addition')),
                ('fixed_override', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='Fixed Rate Override')),
                ('rate_coefficient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_coefficient_modifiers', to='pricing.RateCoefficient', verbose_name='Rate Coefficient')),
            ],
            options={
                'verbose_name': 'Rate Coefficient Modifier',
                'verbose_name_plural': 'Rate Coefficient Modifiers',
            },
        ),
        migrations.CreateModel(
            name='TimeOfDayWorkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('time_start', models.TimeField(default=datetime.time(18, 0), verbose_name='Time From')),
                ('time_end', models.TimeField(default=datetime.time(6, 0), verbose_name='Time To')),
            ],
            options={
                'verbose_name': 'Time of Day Work Rule',
                'verbose_name_plural': 'Time of Day Work Rules',
            },
        ),
        migrations.CreateModel(
            name='WeekdayWorkRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('weekday_monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('weekday_tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('weekday_wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('weekday_thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('weekday_friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('weekday_saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('weekday_sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('weekday_bank_holiday', models.BooleanField(default=False, verbose_name='Bank Holiday')),
            ],
            options={
                'verbose_name': 'Weekday Work Rule',
                'verbose_name_plural': 'Weekday Work Rules',
            },
        ),
        migrations.AddField(
            model_name='ratecoefficient',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Group coefficients across industries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_coefficients', to='pricing.RateCoefficientGroup', verbose_name='Group'),
        ),
        migrations.AddField(
            model_name='pricelistratecoefficient',
            name='rate_coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.RateCoefficient', verbose_name='Rate Coefficient'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='rate_coefficients',
            field=models.ManyToManyField(related_name='price_lists', through='pricing.PriceListRateCoefficient', to='pricing.RateCoefficient', verbose_name='Rate Coefficients'),
        ),
        migrations.AddField(
            model_name='industryratecoefficient',
            name='rate_coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pricing.RateCoefficient', verbose_name='Rate Coefficient'),
        ),
        migrations.AddField(
            model_name='industrypricelist',
            name='industry_rate_coefficients',
            field=models.ManyToManyField(related_name='industry_price_lists', through='pricing.IndustryRateCoefficient', to='pricing.RateCoefficient', verbose_name='Industry Rate Coefficients'),
        ),
        migrations.AddField(
            model_name='dynamiccoefficientrule',
            name='rate_coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_coefficient_rules', to='pricing.RateCoefficient', verbose_name='Rate Coefficient'),
        ),
        migrations.AddField(
            model_name='dynamiccoefficientrule',
            name='rule_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistratecoefficient',
            unique_together=set([('price_list', 'rate_coefficient')]),
        ),
        migrations.AlterUniqueTogether(
            name='industryratecoefficient',
            unique_together=set([('industry_price_list', 'rate_coefficient')]),
        ),
    ]
