# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_add_pricelistrate_defaultrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrypricelist',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='industrypricelist',
            name='industry_rate_coefficients',
        ),
        migrations.RemoveField(
            model_name='industrypricelistrate',
            name='industry_price_list',
        ),
        migrations.RemoveField(
            model_name='industrypricelistrate',
            name='skill',
        ),
        migrations.AlterUniqueTogether(
            name='industryratecoefficient',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='industryratecoefficient',
            name='industry_price_list',
        ),
        migrations.RemoveField(
            model_name='industryratecoefficient',
            name='rate_coefficient',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='industry_price_list',
        ),
        migrations.AddField(
            model_name='ratecoefficient',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rate_coefficients', to='pricing.Industry', verbose_name='Industry'),
        ),
        migrations.DeleteModel(
            name='IndustryPriceList',
        ),
        migrations.DeleteModel(
            name='IndustryPriceListRate',
        ),
        migrations.DeleteModel(
            name='IndustryRateCoefficient',
        ),
    ]
