# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 08:55
from __future__ import unicode_literals

from django.db import migrations


def set_default_industry(apps, schema_editor):
    Industry = apps.get_model("pricing", "Industry")
    RateCoefficient = apps.get_model("pricing", "RateCoefficient")

    industry = Industry.objects.all().first()

    for rate_coeff in RateCoefficient.objects.all():
        rate_coeff.industry = industry
        rate_coeff.save(update_fields=['industry'])


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_removed_industry_price_list'),
    ]

    operations = [
        migrations.RunPython(set_default_industry, migrations.RunPython.noop)
    ]
