# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-26 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_price_list_rate_price_list_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistrate',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='skills.Skill', verbose_name='Skill'),
        ),
    ]
