# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_skill_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='pricelistrate',
            name='price_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='pricing.PriceList', verbose_name='Price List'),
        ),
    ]
