# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_auto_20180625_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='valid_from',
            field=models.DateField(verbose_name='Valid From'),
        ),
    ]
