# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_rename_manager_and_primary_contact'),
        ('pricing', '0010_change_pricelist_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateCoefficientRel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_coefficient_rels', to='core.Company', verbose_name='Company')),
                ('rate_coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_coefficient_rels', to='pricing.RateCoefficient', verbose_name='Rate Coefficient')),
            ],
            options={
                'verbose_name': 'Rate Coefficient Relation',
                'verbose_name_plural': 'Rate Coefficient Relations',
            },
        ),
    ]
