# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_move_used_to_coeff_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecoefficient',
            name='overlaps',
            field=models.BooleanField(default=False, verbose_name='Overlaps'),
        ),
    ]
