# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_ratecoefficient_overlaps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecoefficient',
            name='priority',
            field=models.PositiveIntegerField(default=0, verbose_name='Priority'),
        ),
    ]
