# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-02 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_ratecoefficient_priority_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecoefficientmodifier',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Default'),
        ),
    ]
