# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-02 13:42
from __future__ import unicode_literals

from django.db import migrations


def migrate_coefficient_default(apps, schema_editor):
    RateCoefficient = apps.get_model("pricing", "RateCoefficient")

    for rate_coefficient in RateCoefficient.objects.all():
        rate_coefficient.rate_coefficient_modifiers.filter(type=0).update(default=True)
        rate_coefficient.rate_coefficient_modifiers.filter(type=1).update(default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_ratecoefficientmodifier_default'),
    ]

    operations = [
        migrations.RunPython(migrate_coefficient_default, migrations.RunPython.noop)
    ]
