# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_replace_forms_bank_account'),
        ('pricing', '0020_auto_20191212_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127, verbose_name='Industry transalation')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='pricing.Industry', verbose_name='Industry')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='core.Language', verbose_name='Industry language')),
            ],
            options={
                'verbose_name': 'IndustryLanguage',
                'verbose_name_plural': 'Industry Languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='industrylanguage',
            unique_together=set([('industry', 'language')]),
        ),
    ]
