# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('pricing', '0021_auto_20200712_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistrate',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UnitOfMeasurement', verbose_name='Unit of measurement'),
        ),
    ]
