# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_default_uom(apps, schema_editor):
        UnitOfMeasurement = apps.get_model("core", "UnitOfMeasurement")
        PriceListRate = apps.get_model("pricing", "PriceListRate")
        default_uom = UnitOfMeasurement.objects.get(default=True)
        PriceListRate.objects.all().update(uom=default_uom)

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('skills', '0023_skill_rate_ranges'),
        ('pricing', '0022_pricelistrate_uom'),
    ]

    operations = [
        migrations.RenameField('pricelistrate', 'hourly_rate', 'rate'),
        migrations.AlterField(
            model_name='pricelistrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Rate'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistrate',
            unique_together=set([('price_list', 'skill', 'uom', 'rate')]),
        ),
        migrations.RunPython(set_default_uom),
    ]
