# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('skills', '0025_worktype_worktypelanguage'),
        ('pricing', '0023_add_rate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistrate',
            name='worktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='skills.WorkType', verbose_name='WorkType'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistrate',
            unique_together=set([('price_list', 'skill', 'uom', 'worktype')]),
        ),
    ]
