# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_auto_20210224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrylanguage',
            name='value',
            field=models.CharField(max_length=127, verbose_name='Industry translation'),
        ),
    ]
