# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_fix_typo_industry_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_lists', to='core.CompanyContact', verbose_name='Approved By'),
        ),
    ]
