# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-21 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0033_auto_20210727_1102'),
        ('pricing', '0027_fix_pricelist_approved_by_on_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistrate',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='pricing.PriceList', verbose_name='Price List'),
        ),
        migrations.AlterField(
            model_name='pricelistrate',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='skills.WorkType', verbose_name='WorkType'),
        ),
        migrations.AlterUniqueTogether(
            name='pricelistrate',
            unique_together=set([('price_list', 'worktype')]),
        ),
    ]
