# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_remove_pricelistrate_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistrate',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_rates', to='skills.WorkType', verbose_name='Skill Activity'),
        ),
    ]
