# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0031_auto_20211117_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratecoefficient',
            name='name',
            field=models.CharField(max_length=18, verbose_name='Name'),
        ),
    ]
