# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Using as default for company'),
        ),
    ]
