# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-12 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0002_phonenumber_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sms_interface.SMSTemplate', verbose_name='Template'),
        ),
    ]
