# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_companyworkflownode_order'),
        ('sms_interface', '0003_smsmessage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='Company'),
        ),
    ]
