# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-11 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0005_smsmessage_segments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='segments',
            field=models.IntegerField(default=0, verbose_name='Number of segments'),
        ),
    ]
