# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0008_auto_20191212_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='type',
            field=models.CharField(blank=True, choices=[('SENT', 'SMS sent'), ('RECEIVED', 'SMS received'), ('UNKNOWN', 'SMS Unknown')], default='UNKNOWN', max_length=15, verbose_name='Type'),
        ),
    ]
