# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-03 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20200303_1432'),
        ('sms_interface', '0011_auto_20200220_0748'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together=set([('company', 'name', 'slug')]),
        ),
    ]
