# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-04 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20200404_0825'),
        ('sms_interface', '0012_auto_20200303_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultsmstemplate',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, related_name='default_sms_templates', to='core.Language', verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='defaultsmstemplate',
            unique_together=set([('slug', 'language')]),
        ),
    ]
