# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-04 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20200404_0825'),
        ('sms_interface', '0013_auto_20200404_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='smstemplate',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='core.Language', verbose_name='Template language'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='smstemplate',
            unique_together=set([('company', 'name', 'slug', 'language')]),
        ),
    ]
