# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def change_type_sms_templates(apps, schema_editor):
    SMSTemplate = apps.get_model("sms_interface", "SMSTemplate")
    for template in SMSTemplate.objects.all():
        template.type = 'sms'
        template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0014_auto_20200404_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='type',
            field=models.CharField(choices=[('sms', 'SMS')], default='sms', max_length=8, verbose_name='Type'),
        ),
        migrations.RunPython(change_type_sms_templates),
    ]
