(CONTAINER_ROW, CONTAINER_TABLE, CONTAINER_COLLAPSE, CONTAINER_HIDDEN) = (
    'row', 'table', 'collapse', 'hidden'
)
CONTAINER_TYPES = (CONTAINER_ROW, CONTAINER_TABLE,
                   CONTAINER_COLLAPSE, CONTAINER_HIDDEN)

FIELD_RADIO_GROUP = 'radio_group'
FIELD_CHECKBOX_GROUP = 'checkbox_group'
FIELD_BUTTON = 'button'
FIELD_LINK = 'link'
FIELD_SUBMIT = 'submit'
FIELD_PASSWORD = 'password'
FIELD_RELATED = 'related'
FIELD_STATIC = 'static'
FIELD_SELECT = 'select'
FIELD_DATE = 'date'
FIELD_DATETIME = 'datetime'
FIELD_CHECKBOX = 'checkbox'
FIELD_TEXT = 'text'
FIELD_TEXTAREA = 'textarea'
FIELD_RULE = 'rule'
FIELD_PICTURE = 'picture'
FIELD_FILE = 'file'
FIELD_ICON = 'icon'
FIELD_TIMELINE = 'timeline'

NON_FIELDS_TYPES = (FIELD_BUTTON, FIELD_LINK, FIELD_SUBMIT, FIELD_TIMELINE)

METADATA_LIST_TYPE = 'list'
METADATA_FORM_TYPE = 'form'
METADATA_FORMSET_TYPE = 'formset'
