# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20171102_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('priority', models.SmallIntegerField(choices=[(1, 'Bottom'), (2, 'Low'), (3, 'Normal'), (4, 'High'), (5, 'Top')], default=3, verbose_name='Priority')),
                ('entity_object_id', models.UUIDField(default=None, editable=False, null=True, verbose_name='Related entity id')),
                ('entity_object_name', models.CharField(default='', editable=False, max_length=128, verbose_name='object name')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Starts at')),
                ('ends_at', models.DateTimeField(verbose_name='Ends at')),
                ('done', models.NullBooleanField(choices=[(None, 'New'), (False, 'SEEN'), (True, 'Done')], default=None, verbose_name='Done')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contact', verbose_name='Contact')),
                ('involved_contacts', models.ManyToManyField(blank=True, related_name='involved_in_activities', to='core.Contact', verbose_name='Involved Contacts')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('occur_at', models.DateTimeField(default=None, verbose_name='Occur at')),
                ('status', models.NullBooleanField(choices=[(True, 'Occurred'), (False, 'Fail'), (None, 'Waiting for occur')], default=None, verbose_name='Status')),
                ('error_text', models.TextField(blank=True, default='', verbose_name='Error occurred details')),
                ('activity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occur_dates', to='activity.Activity')),
            ],
            options={
                'verbose_name': 'Activity schedule date',
                'verbose_name_plural': 'Activity schedule dates',
            },
        ),
        migrations.CreateModel(
            name='ActivityRepeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('repeat_type', models.CharField(choices=[('FIXED', 'Fixed'), ('INTERVAL', 'Interval'), ('SCHEDULE', 'Schedule')], default='FIXED', max_length=16, verbose_name='Repeat type')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Started at')),
                ('base_type', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('hourly', 'Hourly'), ('minutely', 'Minutely'), ('secondly', 'Secondly')], default='daily', max_length=16, verbose_name='Schedule type')),
                ('every', models.IntegerField(default=0, verbose_name='Every')),
                ('month_of_year', models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], default=0, verbose_name='Month of Year')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Undefined'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0, verbose_name='Weekday')),
                ('day_of_month', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=0, verbose_name='Day of month')),
                ('hour', models.IntegerField(choices=[(0, '12 AM'), (1, '1 AM'), (2, '2 AM'), (3, '3 AM'), (4, '4 AM'), (5, '5 AM'), (6, '6 AM'), (7, '7 AM'), (8, '8 AM'), (9, '9 AM'), (10, '10 AM'), (11, '11 AM'), (12, '12 PM'), (13, '1 PM'), (14, '2 PM'), (15, '3 PM'), (16, '4 PM'), (17, '5 PM'), (18, '6 PM'), (19, '7 PM'), (20, '8 PM'), (21, '9 PM'), (22, '10 PM'), (23, '11 PM')], default=0, verbose_name='Hour')),
                ('minute', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59)], default=0, verbose_name='Minute')),
                ('tas_key', models.CharField(default='', max_length=512, verbose_name='Task key')),
                ('activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='Activity')),
                ('occurred_activities', models.ManyToManyField(editable=False, related_name='repeaters', to='activity.Activity')),
            ],
            options={
                'verbose_name': 'Activity repeat',
                'verbose_name_plural': 'Activity repeat',
            },
        ),
        migrations.CreateModel(
            name='ActivityTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(db_index=True, default='', max_length=256, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('subject_template', models.CharField(blank=True, default='', max_length=256, verbose_name='Subject template')),
                ('message_text_template', models.TextField(blank=True, default='', verbose_name='Text template')),
                ('message_html_template', models.TextField(blank=True, default='', verbose_name='HTML template')),
                ('reply_timeout', models.IntegerField(default=10, help_text='Minutes', verbose_name='Reply timeout')),
                ('delivery_timeout', models.IntegerField(default=10, help_text='Minutes', verbose_name='Delivery timeout')),
                ('type', models.CharField(choices=[('ACTIVITY', 'Activity')], default='ACTIVITY', max_length=8, verbose_name='Type')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='Master company')),
            ],
            options={
                'verbose_name': 'Activity template',
                'ordering': ['name'],
                'verbose_name_plural': 'Activity templates',
            },
        ),
        migrations.AddField(
            model_name='activitydate',
            name='activity_repeat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repeat_dates', to='activity.ActivityRepeat', verbose_name='Activity repeater'),
        ),
        migrations.AddField(
            model_name='activity',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityTemplate', verbose_name='Template'),
        ),
    ]
