# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_change_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='starts_at',
            field=models.DateTimeField(verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='activitydate',
            name='occur_at',
            field=models.DateTimeField(verbose_name='Occur at'),
        ),
        migrations.AlterField(
            model_name='activityrepeat',
            name='started_at',
            field=models.DateTimeField(verbose_name='Started at'),
        ),
    ]
