# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20191212_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='Master company'),
        ),
    ]
