# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20171102_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='MYOBAuthData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('client_id', models.CharField(help_text='Registered MYOB application API Key', max_length=64, unique=True, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='Registered MYOB application API Secret', max_length=64, unique=True, verbose_name='Client Secret')),
                ('access_token', models.TextField(max_length=2048, verbose_name='Access Token')),
                ('refresh_token', models.CharField(max_length=1024, verbose_name='Refresh Token')),
                ('myob_user_uid', models.CharField(max_length=64, verbose_name='User UID')),
                ('myob_user_username', models.CharField(max_length=512, verbose_name='User Username')),
                ('expires_in', models.PositiveIntegerField(verbose_name='Expires in (seconds)')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at (datetime)')),
            ],
            options={
                'verbose_name': 'MYOB OAuth2 Data',
                'verbose_name_plural': 'MYOB OAuth2 Data',
            },
        ),
        migrations.CreateModel(
            name='MYOBCompanyFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cf_id', models.CharField(max_length=64, unique=True, verbose_name='Company File Id')),
                ('cf_uri', models.CharField(max_length=2048, verbose_name='Uri')),
                ('cf_name', models.CharField(max_length=512, verbose_name='Company File Name')),
            ],
            options={
                'verbose_name': 'MYOB Company File',
                'verbose_name_plural': 'MYOB Company Files',
            },
        ),
        migrations.CreateModel(
            name='MYOBCompanyFileToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cf_token', models.CharField(max_length=32, verbose_name='Company File Token')),
                ('enable_from', models.DateField(blank=True, null=True, verbose_name='Enable From')),
                ('enable_until', models.DateField(blank=True, null=True, verbose_name='Enable Until')),
                ('auth_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myob.MYOBAuthData')),
                ('company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('company_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myob.MYOBCompanyFile')),
            ],
            options={
                'verbose_name': 'MYOB Company File Token',
                'verbose_name_plural': 'MYOB Company File Tokens',
            },
        ),
        migrations.CreateModel(
            name='MYOBRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('method', models.CharField(help_text='Request method', max_length=16, verbose_name='Method')),
                ('url', models.CharField(help_text='Requested URL', max_length=2048, verbose_name='URL')),
                ('headers', models.TextField(blank=True, help_text='Headers sent with request', null=True, verbose_name='Headers')),
                ('data', models.TextField(blank=True, help_text='Request POST data as JSON', null=True, verbose_name='POST data')),
                ('json', models.TextField(blank=True, help_text='Request JSON content', null=True, verbose_name='JSON content')),
                ('params', models.TextField(blank=True, help_text='Request URL params as JSON', null=True, verbose_name='URL parameters')),
                ('kwargs', models.TextField(blank=True, help_text='Additional kwargs to requests method', null=True, verbose_name='kwargs')),
                ('resp_status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='HTTP response code')),
                ('resp_content', models.TextField(blank=True, null=True, verbose_name='Response content')),
                ('resp_json', models.TextField(blank=True, null=True, verbose_name='Response JSON')),
            ],
            options={
                'verbose_name': 'MYOB Request Log',
                'verbose_name_plural': 'MYOB Request Logs',
            },
        ),
        migrations.CreateModel(
            name='MYOBSyncObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('app', models.CharField(max_length=63, verbose_name='App')),
                ('model', models.CharField(max_length=63, verbose_name='Model')),
                ('record', models.UUIDField(verbose_name='Record ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Synced at (datetime)')),
                ('direction', models.CharField(choices=[('myob', 'Django to MYOB'), ('django', 'MYOB to Django')], default='myob', max_length=8, verbose_name='Direction')),
                ('legacy_myob_card_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Legacy MYOB Card Number')),
                ('legacy_confirmed', models.NullBooleanField(verbose_name='Update legacy record')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_objects', to='core.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'MYOB Sync Object',
                'verbose_name_plural': 'MYOB Sync Objects',
            },
        ),
    ]
