# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobcompanyfiletoken',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_file_tokens', to='core.Company'),
        ),
    ]
