# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-06 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myob', '0003_myobcompanyfile_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobauthdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myobauthdata',
            name='client_id',
            field=models.CharField(help_text='Registered MYOB application API Key', max_length=64, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='myobauthdata',
            name='client_secret',
            field=models.CharField(help_text='Registered MYOB application API Secret', max_length=64, verbose_name='Client Secret'),
        ),
        migrations.AlterUniqueTogether(
            name='myobauthdata',
            unique_together=set([('client_id', 'client_secret', 'user')]),
        ),
    ]
