# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0005_update_companyfiletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobsyncobject',
            name='company_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_objects', to='myob.MYOBCompanyFile', verbose_name='MYOB Company File'),
        ),
    ]
