# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0006_myobsyncobject_company_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myobauthdata',
            unique_together=set([]),
        ),
    ]
