# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0006_myobsyncobject_company_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobcompanyfiletoken',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, 'Invoices'), (1, 'Payslips')], default=0, verbose_name='MYOB Company FIle Token type'),
        ),
    ]
