# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-27 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0008_unique_myob_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobcompanyfile',
            name='auth_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myob.MYOBAuthData'),
        ),
    ]
