# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-10 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_admin_access_navigation'),
        ('myob', '0009_myobcompanyfile_auth_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='myobauthdata',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_data', to='core.Company'),
        ),
    ]
