# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-01 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0010_myobauthdata_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobcompanyfiletoken',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_file_tokens', to='core.Company'),
        ),
    ]
