# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-11 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0011_remove_is_null_from_company_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobauthdata',
            name='myob_user_username',
            field=models.CharField(max_length=512, verbose_name='User Username'),
        ),
    ]
