# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-13 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myob', '0012_make_field_myob_username_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myobcompanyfile',
            name='auth_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_file', to='myob.MYOBAuthData'),
        ),
        migrations.AlterField(
            model_name='myobcompanyfiletoken',
            name='auth_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_file_token',
                                    to='myob.MYOBAuthData'),
        ),
    ]
