# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-10 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_add_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content_id', models.IntegerField(default=None, null=True, verbose_name='Content id')),
                ('section', models.CharField(default='1', max_length=8, verbose_name='Section')),
                ('content', models.TextField(verbose_name='Mail message body')),
                ('encoding', models.CharField(default='', max_length=32, verbose_name='Encoding')),
                ('mime', models.TextField(default='', verbose_name='Mime')),
                ('message_mime', models.TextField(default='', verbose_name='Message mime')),
                ('size', models.IntegerField(default=0, verbose_name='Size')),
                ('type', models.CharField(default='text/plain', max_length=32, verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Bodies of E-mail messages',
                'verbose_name': 'Body of E-mail message',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('state', models.CharField(choices=[('CREATED', 'Created'), ('WAIT', 'Waiting'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('ERROR', 'Error')], default='CREATED', max_length=16, verbose_name='State sending')),
                ('message_id', models.CharField(max_length=256, verbose_name='Email message id')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='When mail received')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='When mail received')),
                ('sender_email', models.CharField(default='', max_length=512, verbose_name='Sender email')),
                ('from_email', models.CharField(default='', max_length=512, verbose_name='From email')),
                ('subject', models.TextField(verbose_name='Mail subject')),
                ('headers', models.TextField(default='', verbose_name='Headers')),
                ('to_addresses', models.CharField(blank=True, default='', max_length=1024, verbose_name='Recipients')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date stored in database')),
                ('is_read', models.BooleanField(default=False, verbose_name='Seen')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('error_code', models.TextField(blank=True, default='', null=True, verbose_name='Error code')),
                ('error_message', models.TextField(blank=True, default='', null=True, verbose_name='Error message')),
            ],
            options={
                'verbose_name_plural': 'E-mail messages',
                'verbose_name': 'E-mail message',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(db_index=True, default='', max_length=256, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('subject_template', models.CharField(blank=True, default='', max_length=256, verbose_name='Subject template')),
                ('message_text_template', models.TextField(blank=True, default='', verbose_name='Text template')),
                ('message_html_template', models.TextField(blank=True, default='', verbose_name='HTML template')),
                ('reply_timeout', models.IntegerField(default=10, help_text='Minutes', verbose_name='Reply timeout')),
                ('delivery_timeout', models.IntegerField(default=10, help_text='Minutes', verbose_name='Delivery timeout')),
                ('type', models.CharField(choices=[('email', 'Email')], max_length=8, verbose_name='Type')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company', verbose_name='Master company')),
            ],
            options={
                'verbose_name_plural': 'E-mail Templates',
                'ordering': ['name'],
                'verbose_name': 'E-mail Template',
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_interface.EmailTemplate', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='emailbody',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bodies', to='email_interface.EmailMessage', verbose_name='Email message'),
        ),
    ]
