# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_interface', '0003_change_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='created_at',
            field=models.DateTimeField(editable=False, verbose_name='Created at'),
        ),
    ]
