# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-28 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_interface', '0011_auto_20210406_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='When mail sent'),
        ),
    ]
