# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def combine_template_slugs(apps, schema_editor):
        DefaultEmailTemplate = apps.get_model("email_interface", "DefaultEmailTemplate")
        EmailTemplate = apps.get_model("email_interface", "EmailTemplate")

        for template in DefaultEmailTemplate.objects.filter(slug="consent-email-message"):
            template.slug = "consent-message"
            template.name = "Consent message"
            template.save()

        for template in EmailTemplate.objects.filter(slug="consent-email-message"):
            template.slug = "consent-message"
            template.name = "Consent message"
            template.save()

        for template in DefaultEmailTemplate.objects.filter(slug="forgot-password"):
            template.slug = "generated-password"
            template.name = "Generated password"
            template.save()

        for template in EmailTemplate.objects.filter(slug="forgot-password"):
            template.slug = "generated-password"
            template.name = "Generated password"
            template.save()

        for template in DefaultEmailTemplate.objects.filter(slug="login-email-token"):
            template.slug = "login-token"
            template.name = "Login Token"
            template.save()

        for template in EmailTemplate.objects.filter(slug="login-email-token"):
            template.slug = "login-token"
            template.name = "Login Token"
            template.save()

    dependencies = [
        ('email_interface', '0012_auto_20210428_0505'),
    ]

    operations = [
        migrations.RunPython(combine_template_slugs),
    ]
