# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations


def migrate_recruitee_score(apps, schema_editor):
    CandidateContact = apps.get_model('candidate', 'CandidateContact')
    CandidateScore = apps.get_model('hr', 'CandidateScore')

    for candidate in CandidateContact.objects.all():
        CandidateScore.objects.get_or_create(
            candidate_contact=candidate
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_recruitee_score, migrations.RunPython.noop)
    ]
