# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_candidate_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='hourly_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips', to='skills.SkillBaseRate', verbose_name='Hourly rate'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='candidate_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheets', to='skills.SkillBaseRate', verbose_name='Candidate Rate Override'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='hourly_rate_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='skills.SkillBaseRate', verbose_name='Hourly rate default'),
        ),
        migrations.AlterField(
            model_name='vacancydate',
            name='hourly_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_dates', to='skills.SkillBaseRate', verbose_name='Hourly rate'),
        ),
    ]
