# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-30 15:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_skillbaserate_defaultrate'),
        ('hr', '0003_make_fk_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hourly_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancy_shifts', to='skills.SkillBaseRate', verbose_name='Top hourly rate'),
        ),
        migrations.AddField(
            model_name='shift',
            name='workers',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Workers'),
        ),
    ]
