# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_add_skillbaserate_defaultrate'),
        ('hr', '0004_shift_workers_and_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierlist',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.Skill', verbose_name='Skill'),
        ),
    ]
