# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_carrierlist_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hr.VacancyDate', verbose_name='Date'),
        ),
    ]
