# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-19 10:59
from __future__ import unicode_literals

from django.db import migrations


def create_rules(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    PayslipRule = apps.get_model("hr", "PayslipRule")

    companies = Company.objects.all()

    for company in companies:
        if not company.payslip_rules.all():
            PayslipRule.objects.create(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_candidatescore_average_score'),
    ]

    operations = [
        migrations.RunPython(create_rules)
    ]
