# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0003_smsmessage_template'),
        ('candidate', '0005_update_candidaterel'),
        ('hr', '0010_renamed_vacancy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancyoffer',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_offers', to='candidate.CandidateContact', verbose_name='Candidate contact'),
        ),
        migrations.AlterField(
            model_name='vacancyoffer',
            name='offer_sent_by_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_offers', to='sms_interface.SMSMessage', verbose_name='Offer sent by sms'),
        ),
        migrations.AlterField(
            model_name='vacancyoffer',
            name='reply_received_by_sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_job_offers', to='sms_interface.SMSMessage', verbose_name='Reply received by sms'),
        ),
        migrations.AlterField(
            model_name='vacancyoffer',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='hr.Shift', verbose_name='Shift'),
        ),
        migrations.RenameModel(
            old_name='VacancyOffer',
            new_name='JobOffer',
        ),
        migrations.AlterField(
            model_name='carrierlist',
            name='referral_vacancy_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_carrier_lists', to='hr.JobOffer', verbose_name='Referral Job Offer'),
        ),
        migrations.RenameField(
            model_name='carrierlist',
            old_name='referral_vacancy_offer',
            new_name='referral_job_offer',
        ),
        migrations.AlterField(
            model_name='carrierlist',
            name='vacancy_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_lists', to='hr.JobOffer', verbose_name='Job Offer')
        ),
        migrations.RenameField(
            model_name='carrierlist',
            old_name='vacancy_offer',
            new_name='job_offer',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='vacancy_offer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets', to='hr.JobOffer', verbose_name='Job Offer'),
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='vacancy_offer',
            new_name='job_offer',
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together=set([('job_offer', 'shift_started_at')]),
        ),
    ]
