# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-19 12:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_update_candidaterel'),
        ('skills', '0005_skill_rate_unique_together'),
        ('core', '0022_renamed_job_confirmation_sms_name'),
        ('hr', '0011_renamed_vacaancy_offer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together=set([]),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='customer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_jobs', to='core.Company', verbose_name='Customer Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='customer_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_representative_jobs', to='core.CompanyContact', verbose_name='Customer Representative'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='hourly_rate_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='skills.SkillBaseRate', verbose_name='Hourly rate default'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='jobsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='hr.Jobsite', verbose_name='Jobsite'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='skills.Skill', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='provider_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_jobs', to='core.Company', verbose_name='Provider Company'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='provider_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_representative_jobs', to='core.CompanyContact', verbose_name='Provider Representative'),
        ),
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='Job',
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'Job Offer', 'verbose_name_plural': 'Job Offers'},
        ),
        migrations.AlterField(
            model_name='shiftdate',
            name='vacancy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shift_dates', to='hr.Job', verbose_name='Job'),
        ),
        migrations.RenameField(
            model_name='shiftdate',
            old_name='vacancy',
            new_name='job',
        ),
        migrations.AlterField(
            model_name='shift',
            name='hourly_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_shifts', to='skills.SkillBaseRate', verbose_name='Top hourly rate'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='job_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_sheets', to='hr.JobOffer', verbose_name='Job Offer'),
        ),
        migrations.AlterField(
            model_name='favouritelist',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favouritelists', to='hr.Job', verbose_name='Job'),
        ),
        migrations.RenameField(
            model_name='favouritelist',
            old_name='vacancy',
            new_name='job',
        ),
        migrations.AlterUniqueTogether(
            name='favouritelist',
            unique_together=set([('company_contact', 'candidate_contact', 'company', 'jobsite', 'job')]),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([('work_start_date', 'position', 'jobsite')]),
        ),
    ]
