# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_invoice_approved'),
        ('hr', '0012_renamed_vacancy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AddField(
            model_name='jobsite',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobsites', to='core.Address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='jobsite',
            name='regular_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobsites_regular', to='core.Company', verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsite',
            name='short_name',
            field=models.CharField(blank=True, help_text='Used for jobsite naming', max_length=63, null=True, verbose_name='Site short name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='notes',
            field=models.TextField(blank=True, help_text='Job Description/Instructions for candidate', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='shiftdate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_dates', to='hr.Job', verbose_name='Job'),
        ),
    ]
