# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 12:04
from __future__ import unicode_literals

from django.db import migrations


def migrate_jobsite_addresses(apps, schema_editor):
    JobsiteAddress = apps.get_model('hr', 'JobsiteAddress')

    for jobsite_address in JobsiteAddress.objects.all():
        jobsite = jobsite_address.jobsite
        jobsite.address = jobsite_address.address
        jobsite.regular_company = jobsite_address.regular_company
        jobsite.save(update_fields=['address', 'regular_company'])


def revert_jobsite_addresses(apps, schema_editor):
    Jobsite = apps.get_model('hr', 'Jobsite')
    JobsiteAddress = apps.get_model('hr', 'JobsiteAddress')

    for jobsite in Jobsite.objects.all():
        JobsiteAddress.objects.get_or_create(
            address=jobsite.addressm,
            jobsite=jobsite,
            regular_company=jobsite.regular_company
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_moved_jobsite_address'),
    ]

    operations = [
        migrations.RunPython(migrate_jobsite_addresses, revert_jobsite_addresses)
    ]
