# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-26 12:04
from __future__ import unicode_literals

from django.db import migrations


def migrate_jobsite_notes(apps, schema_editor):
    Jobsite = apps.get_model('hr', 'Jobsite')
    Note = apps.get_model('core', 'Note')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    jobsite_ct = ContentType.objects.filter(app_label='hr', model='jobsite').first()
    if not jobsite_ct:
        return

    for jobsite in Jobsite.objects.all():
        if jobsite.notes:
            Note.objects.get_or_create(object_id=jobsite.id, content_type=jobsite_ct, note=jobsite.notes)


def revert_jobsite_notes(apps, schema_editor):
    Jobsite = apps.get_model('hr', 'Jobsite')
    Note = apps.get_model('core', 'Note')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    jobsite_ct = ContentType.objects.filter(app_label='hr', model='jobsite').first()
    if not jobsite_ct:
        return

    for note in Note.objects.filter(content_type=jobsite_ct):
        Jobsite.objects.filter(id=note.object_id).update(notes=note.note)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0023_invoice_approved'),
        ('hr', '0015_removed_jobsite_address'),
    ]

    operations = [
        migrations.RunPython(migrate_jobsite_notes, revert_jobsite_notes)
    ]
