# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import r3sourcer.apps.hr.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20180530_1745'),
        ('hr', '0016_copy_jobsite_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('verification_evidence', models.FileField(blank=True, null=True, upload_to='', verbose_name='Verification Evidence')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tags', to='hr.Job', verbose_name='Job')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_tags', to='core.Tag', verbose_name='Tag')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_job_tags', to='core.CompanyContact', verbose_name='Verified By')),
            ],
            options={
                'verbose_name_plural': 'Job Tags',
                'verbose_name': 'Job Tag',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobtag',
            unique_together=set([('tag', 'job')]),
        ),
    ]
