# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-08 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_auto_20180625_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paysliprule',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('daily', 'Daily')], default='weekly', max_length=11, verbose_name='Period'),
        ),
    ]
