# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_cleaned_payslip_rule_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
