# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-07 13:21
from __future__ import unicode_literals

from django.db import migrations


def migrate_job_default_rate(apps, schema_editor):
    Job = apps.get_model('hr', 'Job')

    for job in Job.objects.filter(hourly_rate_default__isnull=False):
        job.default_rate = job.hourly_rate_default.hourly_rate
        job.save(update_fields=['default_rate'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_job_default_rate'),
    ]

    operations = [
        migrations.RunPython(migrate_job_default_rate, migrations.RunPython.noop),
    ]
