# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-09 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_remove_job_hourly_rate_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together=set([]),
        ),
    ]
