# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_removed_job_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hourly_rate_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='shiftdate',
            name='hourly_rate_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='candidate_rate_new',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
