# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-27 13:53
from __future__ import unicode_literals

from django.db import migrations


def migrate_hr_default_rate(apps, schema_editor):
    ShiftDate = apps.get_model('hr', 'ShiftDate')
    Shift = apps.get_model('hr', 'Shift')
    TimeSheet = apps.get_model('hr', 'TimeSheet')

    for sd in ShiftDate.objects.filter(hourly_rate__isnull=False):
        sd.hourly_rate_new = sd.hourly_rate.hourly_rate
        sd.save(update_fields=['hourly_rate_new'])

    for shift in Shift.objects.filter(hourly_rate__isnull=False):
        shift.hourly_rate_new = shift.hourly_rate.hourly_rate
        shift.save(update_fields=['hourly_rate_new'])

    for ts in TimeSheet.objects.filter(candidate_rate__isnull=False):
        ts.candidate_rate_new = ts.candidate_rate.hourly_rate
        ts.save(update_fields=['candidate_rate_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_changed_hourly_rate_type'),
    ]

    operations = [
        migrations.RunPython(migrate_hr_default_rate, migrations.RunPython.noop),
    ]
