# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-27 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_move_hr_default_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='shiftdate',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='candidate_rate',
        ),
        migrations.RenameField(
            model_name='shift',
            old_name='hourly_rate_new',
            new_name='hourly_rate'
        ),
        migrations.RenameField(
            model_name='shiftdate',
            old_name='hourly_rate_new',
            new_name='hourly_rate'
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='candidate_rate_new',
            new_name='candidate_rate'
        ),
    ]
