# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-29 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0027_remove_hr_old_rate_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftdate',
            name='workers',
        ),
    ]
