# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sms_interface', '0005_smsmessage_segments'),
        ('hr', '0028_remove_shiftdate_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOfferSMS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offer_smses', to='hr.JobOffer', verbose_name='Job Offer')),
                ('offer_sent_by_sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_offer_smses', to='sms_interface.SMSMessage', verbose_name='Offer sent by sms')),
                ('reply_received_by_sms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_job_offer_smses', to='sms_interface.SMSMessage', verbose_name='Reply received by sms')),
            ],
            options={
                'verbose_name': 'Job Offer SMS',
                'verbose_name_plural': 'Job Offer SMSes',
            },
        ),
    ]
