# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-10 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_move_job_offer_smses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='offer_sent_by_sms',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='reply_received_by_sms',
        ),
    ]
