# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0031_removed_old_job_offer_smses_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatescore',
            name='skill_score',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=3, null=True, verbose_name='Skill Score'),
        ),
    ]
