# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0033_recalc_all_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
        migrations.AlterField(
            model_name='candidateevaluation',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_evaluations', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
        migrations.AlterField(
            model_name='carrierlist',
            name='candidate_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_lists', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
    ]
