# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-20 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0037_auto_20190124_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='supervisor_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Supervisor modified at'),
        ),
    ]
