# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import r3sourcer.apps.hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_change_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='supervisor_approved_scheme',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PIN', 'PIN'), ('SIGNATURE', 'Signature')], default='', editable=False, max_length=16, verbose_name='Supervisor Approved scheme'),
        ),
    ]
