# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-24 20:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0043_change_evaluation_score_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='break_ended_at',
            field=models.DateTimeField(verbose_name='Break Ended at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='break_started_at',
            field=models.DateTimeField(verbose_name='Break Started at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='shift_ended_at',
            field=models.DateTimeField(verbose_name='Shift Ended at'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='shift_started_at',
            field=models.DateTimeField(verbose_name='Shift Started at'),
            preserve_default=False,
        ),
    ]
