# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields
import r3sourcer.apps.hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0045_change_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactjobsitedistancecache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='supervisor_signature',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=r3sourcer.apps.hr.models.TimeSheet.supervisor_signature_path, verbose_name='Supervisor signature'),
        ),
    ]
