# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-13 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0047_auto_20191212_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='break_ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Break Ended at'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='break_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Break Started at'),
        ),
    ]
