# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0048_auto_20200113_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='provider_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_jobs', to='core.Company', verbose_name='Provider Company'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='master_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobsites', to='core.Company', verbose_name='Master company'),
        ),
        migrations.AlterField(
            model_name='jobsite',
            name='regular_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobsites_regular', to='core.Company', verbose_name='Client'),
        ),
    ]
