# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-02 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0050_add_timesheetrate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='wage_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hourly wage'), (1, 'Piecework wage'), (2, 'Combined wage')], default=0, verbose_name='Type of wage'),
        ),
    ]
