# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-20 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0052_timesheet_shift_time_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtag',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='hr.Job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='jobtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tags', to='core.Tag', verbose_name='Tag'),
        ),
    ]
