# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-15 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0032_auto_20210520_1010'),
        ('hr', '0053_auto_20210520_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gob Skill Activity Rate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_rates', to='hr.Job', verbose_name='Job')),
                ('worktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_rates', to='skills.WorkType', verbose_name='Skill activity')),
            ],
            options={
                'verbose_name': 'Job Skill Activity Rate',
                'verbose_name_plural': 'Job Skill Activity Rates',
            },
        ),
        migrations.AlterUniqueTogether(
            name='jobrate',
            unique_together=set([('job', 'worktype')]),
        ),
    ]
