# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-28 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0054_create_JobRate_model'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='timesheet',
        #     name='candidate_notes',
        #     field=models.TextField(blank=True, help_text='Candidate notes for a Timesheet', verbose_name='Candidate Notes'),
        # ),
        # migrations.AddField(
        #     model_name='timesheet',
        #     name='client_notes',
        #     field=models.TextField(blank=True, help_text='Client notes for a Timesheet', verbose_name='Client Notes'),
        # ),
    ]
