# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0056_candidatetimesheetfiles_clienttimesheetfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetrate',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_rates', to='skills.WorkType', verbose_name='Type of work'),
        ),
    ]
