# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-19 14:24
from __future__ import unicode_literals
from r3sourcer.apps.hr.models import TimeSheet

from django.db import migrations


class Migration(migrations.Migration):

    def change_wage_types(apps, schema_editor):
        Job = apps.get_model('hr', 'Job')
        TimeSheet = apps.get_model('hr', 'TimeSheet')

        jobs = Job.objects.filter(wage_type=2)

        for job in jobs:
            job.wage_type = 1
            job.save()


        timesheets = TimeSheet.objects.filter(wage_type=2)

        for timesheet in timesheets:
            timesheet.wage_type = 1
            timesheet.save()



    dependencies = [
        ('hr', '0057_auto_20210715_1345'),
    ]

    operations = [
        migrations.RunPython(change_wage_types)
    ]
