# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-26 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0057_remove_timesheet_files'),
        ('hr', '0058_auto_20210719_1424'),
    ]

    operations = [
    ]
