# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-09-14 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0059_auto_20210726_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetrate',
            name='is_hourly',
            field=models.BooleanField(default=True, verbose_name='Is hourly'),
        ),
    ]
