# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-18 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20211001_1609'),
        ('pricing', '0030_auto_20210824_0905'),
        ('hr', '0060_auto_20210914_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='wage_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hourly wage'), (1, 'Piecework wage')], default=0, verbose_name='Type of wage'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='wage_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Hourly wage'), (1, 'Piecework wage')], default=0, verbose_name='Type of wage'),
        ),
        migrations.AlterUniqueTogether(
            name='jobsite',
            unique_together=set([('industry', 'regular_company', 'short_name')]),
        ),
    ]
