# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-10-20 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0061_auto_20211018_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierlist',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_lists', to='skills.Skill', verbose_name='Skill'),
        ),
    ]
