# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-22 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0062_add_related_name_to_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='wage_type',
        ),
    ]
