# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 15:57
from __future__ import unicode_literals
from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_company_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='/var/www/media/company_pictures/default_picture.jpg', upload_to='company_pictures'),
        ),
    ]
