# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171110_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstorage',
            name='status',
            field=models.NullBooleanField(choices=[(None, 'Wait'), (False, 'Cancelled'), (True, 'Approved')], default=None, verbose_name='Status'),
        ),
    ]
