# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_formstorage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstorage',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_storages', to='core.Company', verbose_name='Company'),
        ),
    ]
