# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('core', '0006_formstorage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='groups',
            field=models.ManyToManyField(related_name='companies', to='auth.Group'),
        ),
    ]
