# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_company_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formfield',
            options={'ordering': ('position',)},
        ),
    ]
