# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_company_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_settings',
        ),
    ]
