# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-07 13:43
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_company_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='contact_pictures/default_picture.jpg', max_length=255, upload_to='contact_pictures'),
        ),
    ]
