# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-15 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_company_company_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint to activate state'),
        ),
    ]
