# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-23 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_create_vat_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.TextField(null=True, verbose_name='Order Number'),
        ),
    ]
