# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-30 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_create_rules'),
        ('core', '0014_update_invoice_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='hr.TimeSheet', verbose_name='TimeSheet'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default='contact_pictures/default_picture.jpg', max_length=255, upload_to='contact_pictures'),
        ),
    ]
