# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-31 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_update_invoice_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='separation_rule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
