# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-08 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_update_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='receive_order_confirmation_sms',
            field=models.BooleanField(default=True, verbose_name='Receive Vacancy confirmation sms'),
        ),
    ]
