# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_invoice_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontact',
            name='timesheet_reminder',
            field=models.BooleanField(default=True, help_text='Unmark when Company Contact does not need timesheet sign reminders', verbose_name='Timesheet Reminder'),
        ),
    ]
