# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-07 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_invoice_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
