# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 10:21
from __future__ import unicode_literals

from django.contrib.auth import get_user_model
from django.db import migrations


def create_and_assign_roles(apps, schema_editor):

    Role = apps.get_model('core', 'Role')
    User = get_user_model()

    roles = {
        'candidate': Role.objects.get_or_create(name='candidate'),
        'manager': Role.objects.get_or_create(name='manager'),
        'client': Role.objects.get_or_create(name='client'),
    }

    for user in User.objects.all():
        try:
            user.role.add(roles[user.access_level])
            user.save()
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_role'),
    ]

    operations = [
        migrations.RunPython(create_and_assign_roles),
    ]
