# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-23 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_renamed_job_confirm_sms_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('manager', 'Manager'), ('client', 'Client'), ('trial', 'Trial')], max_length=255),
        ),
    ]
