# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180423_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
