# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 07:09
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_company_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaddress',
            name='phone_fax',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='companyaddress',
            name='phone_landline',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Landline Phone'),
        ),
    ]
