# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_copy_landline_and_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone_fax',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone_landline',
        ),
    ]
