# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-14 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_labdline_and_fax_from_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycontact',
            name='voip_password',
        ),
        migrations.RemoveField(
            model_name='companycontact',
            name='voip_username',
        ),
    ]
