# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_removed_company_contact_voip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
        ),
    ]
