# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-06 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_skill_on_delete'),
        ('core', '0032_auto_20180530_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='pricing.Industry', verbose_name='Industry'),
        ),
    ]
