# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_short_name(apps, schema_editor):
    Company = apps.get_model("core", "Company")

    Company.objects.all().update(short_name=models.F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_company_short_name'),
    ]

    operations = [
        migrations.RunPython(migrate_short_name, migrations.RunPython.noop)
    ]
