# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_company_short_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmodule',
            name='add_label',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Add button label'),
        ),
        migrations.AddField(
            model_name='dashboardmodule',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='dashboardmodule',
            name='endpoint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endpoint'),
        ),
    ]
