# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-19 09:07
from __future__ import unicode_literals

from django.db import migrations

from r3sourcer.apps.core_adapter.utils import api_reverse_lazy


def migrate_dashboard(apps, schema_editor):
    DashboardModule = apps.get_model("core", "DashboardModule")
    ContentType = apps.get_model("contenttypes", "ContentType")

    DashboardModule.objects.update_or_create(
        content_type=ContentType.objects.get(app_label='candidate', model='candidatecontact'),
        endpoint=api_reverse_lazy('candidate/candidatecontacts'),
        defaults={'label': 'Candidates'}
    ),
    DashboardModule.objects.update_or_create(
        content_type=ContentType.objects.get(app_label='core', model='company'),
        endpoint=api_reverse_lazy('core/companies'),
        defaults={'label': 'Clients'}
    ),
    DashboardModule.objects.update_or_create(
        content_type=ContentType.objects.get(app_label='core', model='companycontact'),
        endpoint=api_reverse_lazy('core/companycontacts'),
        defaults={'label': 'Client contacts'}
    ),


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_dashboardmodule_label'),
    ]

    operations = [
        migrations.RunPython(migrate_dashboard, migrations.RunPython.noop)
    ]
