# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_added_label_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='company_contact_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.CompanyContactRelationship', verbose_name='Company Contact Relation'),
        ),
    ]
