# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-20 07:19
from __future__ import unicode_literals

from django.db import migrations

from r3sourcer.apps.core_adapter.utils import api_reverse_lazy


def migrate_dashboard(apps, schema_editor):
    DashboardModule = apps.get_model("core", "DashboardModule")
    ContentType = apps.get_model("contenttypes", "ContentType")

    DashboardModule.objects.update_or_create(
        content_type=ContentType.objects.get(app_label='candidate', model='candidatecontact'),
        endpoint=api_reverse_lazy('candidate/candidatecontacts'),
        defaults={
            'label': 'Candidate contacts',
            'description': 'Open full list with candidate contacts',
            'add_label': '+ Add new candidate contact',
        }
    ),


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_added_label_dashboard'),
    ]

    operations = [
        migrations.RunPython(migrate_dashboard, migrations.RunPython.noop)
    ]
