# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-19 13:13
from __future__ import unicode_literals

from django.db import migrations

from r3sourcer.apps.core.models import Role, Company


def migrate_dashboard(apps, schema_editor):
    CompanyContactRelationship = apps.get_model("core", "CompanyContactRelationship")
    Role_model = apps.get_model("core", "Role")

    for company_contact_rel in CompanyContactRelationship.objects.all():
        if company_contact_rel.company.type == Company.COMPANY_TYPES.master:
            continue

        user = company_contact_rel.company_contact.contact.user
        if user:
            role = user.role.filter(company_contact_rel__isnull=True, name=Role.ROLE_NAMES.client).first()
            if not role:
                user.role.add(Role_model.objects.create(
                    company_contact_rel=company_contact_rel, name=Role.ROLE_NAMES.client
                ))
            else:
                role.company_contact_rel = company_contact_rel
                role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_user_role_company_contact'),
    ]

    operations = [
        migrations.RunPython(migrate_dashboard, migrations.RunPython.noop)
    ]
