# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-21 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_set_role_to_company_contact'),
        ('core', '0043_renamed_candidate_dashboard'),
    ]

    operations = [
    ]
