# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-22 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20180621_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='initial',
            field=models.BooleanField(default=False, verbose_name='Is initial state'),
        ),
    ]
