# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20180621_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_addresses', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyrel',
            name='regular_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_companies', to='core.Company', verbose_name='Regular company'),
        ),
        migrations.AlterField(
            model_name='companytradereference',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_trade_references', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_invoices', to='core.Company', verbose_name='Customer Company'),
        ),
        migrations.AlterField(
            model_name='invoicerule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_rules', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='core.Company', verbose_name='Customer Company'),
        ),
    ]
