# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-27 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180625_1759'),
        ('core', '0046_workflownode_initial'),
    ]

    operations = [
    ]
