# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_merge_20180627_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerule',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly'), ('daily', 'Daily')], default='weekly', max_length=11, verbose_name='Period'),
        ),
    ]
