# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_removed_prepaid_invoice_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='confidential',
            field=models.BooleanField(default=False, verbose_name='Confidential'),
        ),
    ]
