# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-09 08:45
from __future__ import unicode_literals

from django.db import migrations

from r3sourcer.apps.core.models import Company


def reassign_client_terms(apps, schema_editor):
    CompanyModel = apps.get_model('core', 'Company')

    CompanyModel.objects.filter(terms_of_payment__in=[
        Company.TERMS_PAYMENT_CHOICES.day_of_month,
        Company.TERMS_PAYMENT_CHOICES.day_of_month_eom
    ]).update(terms_of_payment=Company.TERMS_PAYMENT_CHOICES.on_delivery)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_tag_confidential'),
    ]

    operations = [
        migrations.RunPython(reassign_client_terms, migrations.RunPython.noop)
    ]
