# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_renamed_days_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formstorage',
            name='company',
        ),
        migrations.RemoveField(
            model_name='formstorage',
            name='form',
        ),
        migrations.DeleteModel(
            name='FormStorage',
        ),
    ]
