# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 09:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_removed_form_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Available fields'),
        ),
    ]
