# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_formbuilder_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.WorkflowNode', verbose_name='Parent Node'),
        ),
        migrations.AddField(
            model_name='workflownode',
            name='full_path',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='Full path'),
        ),
    ]
