# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 13:49
from __future__ import unicode_literals

from django.db import migrations


def generate_workflownodes_path(apps, schema_editor):
    WorkflowNode = apps.get_model('core', 'WorkflowNode')

    for node in WorkflowNode.objects.all():
        node.full_path = str(node.number)
        node.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_workflownode_parent_path'),
    ]

    operations = [
        migrations.RunPython(generate_workflownodes_path, migrations.RunPython.noop)
    ]
