# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_workflownode_fill_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='full_path',
            field=models.CharField(editable=False, max_length=32, verbose_name='Full path'),
        ),
    ]
