# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_wf_node_company(apps, schema_editor):
    WorkflowNode = apps.get_model('core', 'WorkflowNode')
    CompanyWorkflowNode = apps.get_model('core', 'CompanyWorkflowNode')

    for node in WorkflowNode.objects.all():
        if node.company is not None:
            CompanyWorkflowNode.objects.get_or_create(company=node.company, workflow_node=node)


def reverse_wf_node_company(apps, schema_editor):
    CompanyWorkflowNode = apps.get_model('core', 'CompanyWorkflowNode')

    for company_node in CompanyWorkflowNode.objects.all():
        node = company_node.workflow_node
        node.company = company_node.company
        node.save(update_fields=['company'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_workflownode_path_readonly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkflowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow_nodes', to='core.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name_plural': 'Company Workflow Nodes',
                'verbose_name': 'Company Workflow Node',
            },
        ),
        migrations.AddField(
            model_name='workflownode',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='companyworkflownode',
            name='workflow_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_workflow_nodes', to='core.WorkflowNode', verbose_name='Workflow Node'),
        ),
        migrations.RunPython(
            code=migrate_wf_node_company,
            reverse_code=reverse_wf_node_company,
        ),
        migrations.AlterUniqueTogether(
            name='companyworkflownode',
            unique_together=set([('company', 'workflow_node')]),
        ),
        migrations.AlterUniqueTogether(
            name='workflownode',
            unique_together=set([('number', 'workflow')]),
        ),
        migrations.RemoveField(
            model_name='workflownode',
            name='company',
        ),
    ]
