# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-11 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_workflow_node_relation_to_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflownode',
            unique_together=set([]),
        ),
    ]
