# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-18 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_removed_wf_company_node_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworkflownode',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
