# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-13 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_companyworkflownode_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
