# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-13 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_form_builder_initial_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sms_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
