# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_contact_sms_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='core.CompanyContact', verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_primary_addresses', to='core.CompanyContact', verbose_name='Primary contact'),
        ),
        migrations.AlterField(
            model_name='companycontactaddress',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_addresses', to='core.CompanyContact', verbose_name='Company Contact'),
        ),
        migrations.AlterField(
            model_name='companyrel',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_accounts', to='core.CompanyContact', verbose_name='Primary Contact'),
        ),
    ]
