# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-09-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_master_company_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extranetnavigation',
            name='access_level',
            field=models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('candidate', 'Candidate'), ('admin', 'Admin')], default='manager', max_length=63, verbose_name='Acess Level'),
        ),
    ]
