# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 06:57
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_admin_access_navigation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='formfield',
            managers=[
                ('inheritance_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
