# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_change_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
