# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_change_form_active_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='verification_token',
            field=models.CharField(default='', max_length=64),
        ),
    ]
