# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 10:09
from __future__ import unicode_literals

from django.db import migrations


def update_form_builder(apps, schema_builder):
    FormBuilder = apps.get_model('core', 'FormBuilder')
    CandidateContact = apps.get_model('candidate', 'CandidateContact')

    from r3sourcer.apps.core.models import ModelFormField, FormFieldGroup, Form

    candidate_builder = FormBuilder.objects.filter(content_type__model__iexact='candidatecontact').first()
    if not candidate_builder:
        return

    candidate_builder.required_fields = [
        'contact__first_name', 'contact__last_name', 'contact__email', 'contact__phone_mobile',
        'contact__address__street_address', 'contact__address__city', 'contact__address__postal_code',
        'contact__address__state', 'contact__address__country'
    ]
    candidate_builder.active_fields = [
        'contact__first_name', 'contact__last_name', 'contact__email', 'contact__phone_mobile'
    ]
    candidate_builder.save()

    for candidate_form in Form.objects.filter(builder_id=candidate_builder.id):
        if candidate_form.groups.exists():
            continue

        group = FormFieldGroup.objects.create(form=candidate_form, name='default')

        model_fields = ModelFormField.get_model_fields(
            CandidateContact,
            builder=candidate_builder
        )
        model_fields = ModelFormField.flatten_model_fields_config(model_fields)

        for order, active_field in enumerate(candidate_builder.active_fields):
            if active_field not in candidate_builder.fields:
                continue

            ModelFormField.objects.create(
                group=group,
                label=model_fields[active_field]['label'],
                name=active_field,
                position=order,
                required=model_fields[active_field]['required'],
                help_text=model_fields[active_field]['help_text'],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_form_builder_required_fields'),
    ]

    operations = [
        migrations.RunPython(update_form_builder, migrations.RunPython.noop)
    ]
