# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 09:15
from __future__ import unicode_literals

from django.db import migrations


def migrate_dashboard(apps, schema_editor):
    DashboardModule = apps.get_model("core", "DashboardModule")

    for dashboard_module in DashboardModule.objects.all():
        dashboard_module.endpoint = dashboard_module.endpoint.replace('/ecore/api/v2', '')
        dashboard_module.save()


def reverse_dashboard(apps, schema_editor):
    DashboardModule = apps.get_model("core", "DashboardModule")

    for dashboard_module in DashboardModule.objects.all():
        dashboard_module.endpoint = '/ecore/api/v2{}'.format(dashboard_module.endpoint)
        dashboard_module.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_update_form_buider'),
    ]

    operations = [
        migrations.RunPython(migrate_dashboard, reverse_dashboard),
    ]
