# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0075_update_dashboard_endpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedFormField',
            fields=[
                ('formfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.FormField')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='Allow Multiple Selections')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type for field')),
            ],
            options={
                'verbose_name': 'Related field',
                'verbose_name_plural': 'Related fields',
            },
            bases=('core.formfield',),
        ),
    ]
