# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0076_relatedformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilderExtraFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.SlugField(verbose_name='Name')),
                ('label', models.CharField(blank=True, default='', max_length=512, verbose_name='Label')),
                ('placeholder', models.CharField(blank=True, max_length=512, verbose_name='Placeholder')),
                ('help_text', models.CharField(blank=True, max_length=512, verbose_name='Help text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('builder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_fields', to='core.FormBuilder', verbose_name='Form Builder')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_builder_fields', to='contenttypes.ContentType', verbose_name='Content type for field')),
                ('related_through_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_builder_through_fields', to='contenttypes.ContentType', verbose_name='Content type of related model')),
            ],
            options={
                'verbose_name': 'Form Builder Extra Field',
                'verbose_name_plural': 'Form Builder Extra Fields',
            },
        ),
    ]
