# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 07:53
from __future__ import unicode_literals

from django.db import migrations


def add_form_builder(apps, schema_builder):
    FormBuilder = apps.get_model('core', 'FormBuilder')
    FormBuilderExtraFields = apps.get_model('core', 'FormBuilderExtraFields')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    candidate_builder = FormBuilder.objects.filter(content_type__model__iexact='candidatecontact').first()
    if not candidate_builder:
        return

    FormBuilderExtraFields.objects.create(
        builder=candidate_builder,
        name='skill',
        label='Skills',
        content_type=ContentType.objects.get(model__iexact='skill'),
        related_through_content_type=ContentType.objects.get(model__iexact='skillrel')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_formbuilderextrafields'),
    ]

    operations = [
        migrations.RunPython(add_form_builder, migrations.RunPython.noop)
    ]
