# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_add_skill_form_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='manager',
            new_name='primary_contact',
        ),
        migrations.RenameField(
            model_name='companyrel',
            old_name='primary_contact',
            new_name='manager',
        ),
    ]
