# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-19 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_rename_manager_and_primary_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_period_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Trial Period Start'),
        ),
    ]
