# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_added_synced_at_to_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='timesheet_approval_scheme',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PIN', 'PIN'), ('SIGNATURE', 'Signature')], default='BASIC', max_length=16, verbose_name='TimeSheet approval scheme'),
        ),
    ]
