# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_added_new_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vat',
            name='stripe_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Stripe Tax percentage', max_digits=16, verbose_name='Stripe Rate'),
        ),
    ]
