# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_added_stripe_tax_to_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_rating',
        ),
        migrations.AddField(
            model_name='company',
            name='purpose',
            field=models.CharField(choices=[('hire', 'Hire'), ('self_use', 'Self Use'), ('recruitment', 'Recruitment')], default='hire', max_length=20, verbose_name='Porpose'),
        ),
    ]
