# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_add_purpose_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustryRel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company Industry Relation',
                'verbose_name_plural': 'Company Industries Relation',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='old_companies', to='pricing.Industry', verbose_name='Industries'),
        ),
        migrations.AddField(
            model_name='companyindustryrel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry_rels', to='core.Company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companyindustryrel',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_industry_rels', to='pricing.Industry', verbose_name='Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, through='core.CompanyIndustryRel', to='pricing.Industry', verbose_name='Industry'),
        ),
    ]
