# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-15 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_migrate_industry_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
