# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-07-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_old_industry_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_timezone',
            field=models.CharField(blank=True, max_length=126, null=True),
        ),
    ]
