# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-21 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_add_company_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardmodule',
            name='endpoint',
            field=models.CharField(max_length=255, verbose_name='Endpoint'),
            preserve_default=False,
        ),
    ]
