# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-28 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_change_dashboard_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=8, null=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='invoicerule',
            name='serial_number',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Serial number'),
        ),
    ]
