# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-09 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20200303_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Apartment'),
        ),
    ]
