# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-11 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_address_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='myob_card_id',
            field=models.CharField(default='-', max_length=15),
            preserve_default=False,
        ),
    ]
