# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_contact_myob_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='old_myob_card_id',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='myob_card_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
