# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-11 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def propagate_default_myob_card_id(apps, schema_editor):
        Contact = apps.get_model("core", "Contact")
        for contact in Contact.objects.all():
            contact.myob_card_id = str(contact.id)[-15:]
            contact.save()

    dependencies = [
        ('core', '0100_auto_20200311_1328'),
    ]

    operations = [
        migrations.RunPython(propagate_default_myob_card_id),
    ]
