# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-21 14:32
from __future__ import unicode_literals
import pycountry

from django.db import migrations, models


def propagate_languages(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    languages = []
    for language in pycountry.languages:
        lang = Language(
            alpha_2=getattr(language, 'alpha_2', '--'),
            alpha_3=getattr(language, 'alpha_3', '---'),
            name=language.name
        )
        languages.append(lang)
    Language.objects.bulk_create(languages)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0101_auto_20200311_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_2', models.CharField(default='--', max_length=2)),
                ('alpha_3', models.CharField(default='---', max_length=3)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.RunPython(propagate_languages),
    ]
