# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-21 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pycountry


def clean_languages(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    Language.objects.all().delete()


def propagate_languages(apps, schema_editor):
    Language = apps.get_model("core", "Language")
    languages = []
    for language in pycountry.languages:
        if not hasattr(language, 'alpha_2'):
            continue
        lang = Language(alpha_2=language.alpha_2, name=language.name)
        languages.append(lang)
    Language.objects.bulk_create(languages)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_language'),
    ]

    operations = [
        migrations.RunPython(clean_languages),
        migrations.RemoveField(
            model_name='language',
            name='alpha_3',
        ),
        migrations.RemoveField(
            model_name='language',
            name='id',
        ),
        migrations.AlterField(
            model_name='language',
            name='alpha_2',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
        migrations.RunPython(propagate_languages),
    ]
