# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-04 08:51
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def propagate_default_company_language(apps, schema_editor):
    Company = apps.get_model("core", "Company")
    CompanyLanguage = apps.get_model("core", "CompanyLanguage")
    languages = []
    for company in Company.objects.filter(type='master', languages__isnull=True).all():
        languages.append(CompanyLanguage(company=company,
                                         language_id=settings.DEFAULT_LANGUAGE,
                                         default=True))
    CompanyLanguage.objects.bulk_create(languages)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20200404_0825'),
    ]

    operations = [
        migrations.RunPython(propagate_default_company_language),
    ]
