# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-10 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20200404_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bank account field',
                'verbose_name_plural': 'Bank account fields',
            },
        ),
        migrations.CreateModel(
            name='BankAccountFieldLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('default', models.BooleanField(default=False)),
                ('ba_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.BankAccountField', verbose_name='Bank account field language')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_account_fields', to='core.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Bank account field language',
                'verbose_name_plural': 'Bank account field languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankaccountfieldlanguage',
            unique_together=set([('ba_field', 'language')]),
        ),
    ]
