# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_auto_20200410_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('description', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Bank account layout',
                'verbose_name_plural': 'Bank account layouts',
            },
        ),
        migrations.CreateModel(
            name='BankAccountLayoutField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='core.BankAccountField', verbose_name='Bank account field')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='core.BankAccountLayout', verbose_name='Bank account layout')),
            ],
            options={
                'verbose_name': 'Bank account layout field',
                'verbose_name_plural': 'Bank account layout fields',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankaccountlayoutfield',
            unique_together=set([('field', 'layout')]),
        ),
    ]
