# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_auto_20200410_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccountLayoutCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='core.Country', to_field='code2', verbose_name='Country')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries', to='core.BankAccountLayout', verbose_name='Bank account layout')),
            ],
            options={
                'verbose_name': 'Bank account layout country',
                'verbose_name_plural': 'Bank account layout countries',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankaccountlayoutcountry',
            unique_together=set([('country', 'layout')]),
        ),
    ]
