# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-11 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20200410_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.Contact', verbose_name='Contact')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BankAccountLayout', verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'Contact Bank account',
                'verbose_name_plural': 'Contact Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='ContactBankAccountField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('value', models.CharField(blank=True, max_length=128, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.ContactBankAccount', verbose_name='Bank account')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.BankAccountField', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'Contact Bank account field',
                'verbose_name_plural': 'Contact Bank account fields',
            },
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts_old', to='core.Contact', verbose_name='Contact'),
        ),
    ]
