# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_auto_20200411_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountlayout',
            name='payment_system',
            field=models.CharField(choices=[('MYOB', 'MYOB payment system'), ('OTHER', 'Other payment system')], default='OTHER', max_length=25, verbose_name='Payment system'),
        ),
    ]
