# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_bankaccountlayout_payment_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccountlayoutfield',
            name='order',
            field=models.SmallIntegerField(default=0),
        ),
    ]
