# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-27 11:25
from __future__ import unicode_literals

from django.db import migrations


def propagate_bank_accounts(apps, schema_editor):
    BankAccountLayout = apps.get_model("core", "BankAccountLayout")
    BankAccount = apps.get_model("core", "BankAccount")
    ContactBankAccount = apps.get_model("core", "ContactBankAccount")
    ContactBankAccountField = apps.get_model("core", "ContactBankAccountField")
    old_bank_account_fields = ['bsb', 'bank_account_name', 'account_number', 'bank_name']
    layouts = BankAccountLayout.objects.filter(payment_system='MYOB').all()
    for layout in layouts:
        field_id_map = {}
        for field in layout.fields.all():
            for old_field in old_bank_account_fields:
                if old_field in field.field.name:
                    field_id_map[old_field] = field.field.id

        for bank_account in BankAccount.objects.all():
            contact_bank_account = ContactBankAccount(
                contact_id=bank_account.contact_id,
                layout_id=layout.pk
            )
            fields = []
            for k, v in field_id_map.items():
                contact_bank_account_field = ContactBankAccountField(
                    bank_account=contact_bank_account,
                    field_id=v,
                    value=getattr(bank_account, k)
                )
                fields.append(contact_bank_account_field)
            contact_bank_account.save()
            ContactBankAccountField.objects.bulk_create(fields)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_bankaccountlayoutfield_order'),
    ]

    operations = [
        migrations.RunPython(propagate_bank_accounts),
    ]
