# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20200427_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontact',
            name='approved_by_primary_contact',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_approvals', to='core.Contact', verbose_name='Approved by primary contact'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='approved_by_staff',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_approvals', to='core.Contact', verbose_name='Approved by staff'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contact', to='core.Contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='contactbankaccount',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.Contact', verbose_name='Contact'),
        ),
    ]
