# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20200515_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycontactrelationship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='companyrel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_accounts', to='core.CompanyContact', verbose_name='Primary Contact'),
        ),
        migrations.AlterField(
            model_name='companyrel',
            name='master_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_companies', to='core.Company', verbose_name='Master company'),
        ),
        migrations.AlterField(
            model_name='form',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='core.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_invoices', to='core.Company', verbose_name='Provider Company'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_orders', to='core.Company', verbose_name='Provider Company'),
        ),
        migrations.AlterField(
            model_name='sitecompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_companies', to='core.Company', verbose_name='Company'),
        ),
    ]
