# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20200515_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts_old', to='core.Contact', verbose_name='Contact'),
        ),
    ]
