# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20200520_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='myob_card_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='old_myob_card_id',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
