# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20200529_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='core.Contact', verbose_name='Contact language')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to='core.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name': 'Contact language',
                'verbose_name_plural': 'Contact languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='contactlanguage',
            unique_together=set([('contact', 'language')]),
        ),
    ]
