# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-29 20:39
from __future__ import unicode_literals

from django.db import migrations


def replace_forms_bank_account(apps, schema_editor):
    FormBuilder = apps.get_model('core', 'FormBuilder')

    for form_builder in FormBuilder.objects.all():
        form_builder.fields = [
            'contact__bank_accounts' if field == 'bank_account' else field
            for field in form_builder.fields
        ]
        form_builder.save()


def reverse(apps, schema_editor):
    FormBuilder = apps.get_model('core', 'FormBuilder')

    for form_builder in FormBuilder.objects.all():
        form_builder.fields = [
            'bank_account' if field == 'contact__bank_accounts' else field
            for field in form_builder.fields
        ]
        form_builder.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20200611_1300'),
    ]

    operations = [
        migrations.RunPython(replace_forms_bank_account, reverse)
    ]
