# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-12 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_replace_forms_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=127, verbose_name='Tag transalation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_names', to='core.Language', verbose_name='Tag name language')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Tag', verbose_name='Tag Name')),
            ],
            options={
                'verbose_name': 'Tag Language',
                'verbose_name_plural': 'Tag Languages',
            },
        ),
        migrations.AlterUniqueTogether(
            name='taglanguage',
            unique_together=set([('tag', 'language')]),
        ),
    ]
