# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-18 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20200712_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Tag',
                'verbose_name_plural': 'Company Tags',
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.CharField(choices=[('system', 'System'), ('company', 'Company')], default='system', max_length=10),
        ),
        migrations.AddField(
            model_name='companytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='core.Tag', verbose_name='Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='companytag',
            unique_together=set([('tag', 'company')]),
        ),
    ]
