# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-27 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_auto_20200718_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCompany',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.tag',),
        ),
        migrations.AlterField(
            model_name='companytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='core.TagCompany', verbose_name='Tag company'),
        ),
    ]
