# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-27 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_auto_20200727_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcompany',
            options={'verbose_name': 'Tag owned by company', 'verbose_name_plural': 'Tags owned by company'},
        ),
    ]
