# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20201103_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='has_separate_personal_id',
            field=models.NullBooleanField(verbose_name='Has Personal ID'),
        ),
    ]
