# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-05 18:45 update
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_copy_address_to_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
    ]
