# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-08 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_remove_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
