# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-08 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_add_is_active_to_contactaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalid',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='taxnumber',
            name='contact_address',
        ),
        migrations.DeleteModel(
            name='PersonalID',
        ),
        migrations.DeleteModel(
            name='TaxNumber',
        ),
    ]
