# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-09 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_remove_taxnumber_personalid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('value', models.CharField(max_length=64, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Personal ID',
                'verbose_name_plural': 'Personal IDs',
            },
        ),
        migrations.CreateModel(
            name='TaxNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('value', models.CharField(max_length=64, verbose_name='Value')),
                ('contact_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_number', to='core.ContactAddress', verbose_name='Contact address')),
            ],
            options={
                'verbose_name': 'Tax Number',
                'verbose_name_plural': 'Tax Numbers',
            },
        ),
    ]
