# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-15 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_add_taxnumber_personalid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formlanguage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='formlanguage',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formlanguage',
            name='language',
        ),
        migrations.DeleteModel(
            name='FormLanguage',
        ),
    ]
