# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-16 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    def propagate_default_formlanguage(apps, schema_editor):
        Form = apps.get_model("core", "Form")
        FormLanguage = apps.get_model("core", "FormLanguage")

        # language_obj = Language.objects.get(alpha_2="en")
        for form in Form.objects.all():
            FormLanguage.objects.create(form=form,
                                        language_id="en",
                                        title="Application Form",
                                        short_description="New application form",
                                        button_text="Save",
                                        result_messages="You've been registered!")

    dependencies = [
        ('core', '0137_fake_migration_formlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLanguage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('title', models.CharField(default='Application Form', max_length=64, verbose_name='Form Title')),
                ('short_description', models.CharField(default='New application form', max_length=255, verbose_name='Form Short Description')),
                ('button_text', models.CharField(default='Save', max_length=32, verbose_name='Form Button Text')),
                ('result_messages', models.CharField(default='Your form has been saved', max_length=255, verbose_name='Form Result Message')),
            ],
            options={
                'verbose_name': 'Form translations',
            },
        ),
        migrations.RemoveField(
            model_name='form',
            name='save_button_text',
        ),
        migrations.RemoveField(
            model_name='form',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='form',
            name='submit_message',
        ),
        migrations.RemoveField(
            model_name='form',
            name='title',
        ),
        migrations.AddField(
            model_name='form',
            name='active_language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='core.Language', verbose_name='Active Language'),
        ),
        migrations.AddField(
            model_name='formlanguage',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='core.Form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='formlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formlanguages', to='core.Language', verbose_name='Form language'),
        ),
        migrations.AlterUniqueTogether(
            name='formlanguage',
            unique_together=set([('form', 'language')]),
        ),
        migrations.RunPython(propagate_default_formlanguage),
    ]
