# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-28 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_formlanguage_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalid',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='taxnumber',
            name='contact_address',
        ),
        migrations.DeleteModel(
            name='PersonalID',
        ),
        migrations.DeleteModel(
            name='TaxNumber',
        ),
    ]
