# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_auto_20201228_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='regex',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Regex Pattern'),
        ),
        migrations.AlterField(
            model_name='country',
            name='personal_id_type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Personal ID number type'),
        ),
    ]
