# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_auto_20210106_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=32, verbose_name='Unit name', unique=True)),
                ('short_name', models.CharField(max_length=16, verbose_name='Unit short name', unique=True)),
                ('default', models.BooleanField(default=False, verbose_name='Default unit of measurement')),
            ],
            options={
                'verbose_name': 'Unit of measurement',
                'verbose_name_plural': 'Units of measurement',
            },
        ),
        migrations.CreateModel(
            name='UOMLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='UOM name translation')),
                ('short_name', models.CharField(max_length=16, verbose_name='UOM short name translation')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uomlanguages', to='core.Language', verbose_name='Language')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.UnitOfMeasurement', verbose_name='Unit of measurement')),
            ],
            options={
                'verbose_name': 'UOM translations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='uomlanguage',
            unique_together=set([('uom', 'language')]),
        ),
    ]
