# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-09 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    def load_default_uoms_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "uom")

    def delete_default_uoms(apps, schema_editor):
        UnitOfMeasurement = apps.get_model("core", "UnitOfMeasurement")
        UnitOfMeasurement.objects.all().delete()

    def load_sms_uom_languages_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "uom_lang")

    def delete_uom_languages(apps, schema_editor):
        UOMLanguage = apps.get_model("core", "UOMLanguage")
        UOMLanguage.objects.all().delete()


    dependencies = [
        ('core', '0141_auto_20210108_1513'),
    ]

    operations = [
        migrations.RunPython(load_default_uoms_from_fixture,
                             delete_default_uoms),
        migrations.RunPython(load_sms_uom_languages_from_fixture,
                             delete_uom_languages),
    ]
