# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_add_extranet_navigation_data'),
        ('core', '0142_auto_20210109_1110'),
    ]

    operations = [
    ]
