# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-14 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from r3sourcer.apps.core.models import Company, CompanyContact, CompanyContactRelationship




class Migration(migrations.Migration):

    def delete_duplicated_companycontactrelationship(apps, schema_editor):
        Company = apps.get_model("core", "Company")
        CompanyContact = apps.get_model("core", "CompanyContact")
        CompanyContactRelationship = apps.get_model("core", "CompanyContactRelationship")

        for company in Company.objects.all():
            for company_contact in CompanyContact.objects.all():
                rels = CompanyContactRelationship.objects.filter(company=company, company_contact=company_contact)
                if rels.count() > 0:
                    first_rel = rels.first()
                    CompanyContactRelationship.objects.filter(company=company, company_contact=company_contact) \
                                                       .exclude(pk=first_rel.pk) \
                                                       .delete()

    dependencies = [
        ('core', '0143_merge_20210212_0605'),
    ]

    operations = [
        migrations.RunPython(delete_duplicated_companycontactrelationship),
    ]
