# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_delete_duplicated_relations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycontactrelationship',
            options={'verbose_name': 'Company Contact Relationship', 'verbose_name_plural': 'Company Contact Relationships'},
        ),
        migrations.AlterField(
            model_name='formlanguage',
            name='language',
            field=models.ForeignKey(default='en', on_delete=django.db.models.deletion.CASCADE, related_name='formlanguages', to='core.Language', verbose_name='Form language'),
        ),
        migrations.AlterUniqueTogether(
            name='companycontactrelationship',
            unique_together=set([('company', 'company_contact')]),
        ),
    ]
