# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import r3sourcer.apps.core.models.core
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_make_company_contact_relation_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('file', models.FileField(
                    upload_to=r3sourcer.apps.core.models.core.NoteFile.note_files_path,
                    verbose_name='Note File')),
            ],
            options={
                'verbose_name': 'Note File',
                'verbose_name_plural': 'Note Files',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notes', to='core.Contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='notefile',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.Note', verbose_name='Note'),
        ),
    ]
