# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-12-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20211001_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='card_number',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
