# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-09 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatecontact',
            name='message_by_email',
            field=models.BooleanField(default=True, verbose_name='By E-Mail'),
        ),
        migrations.AddField(
            model_name='candidatecontact',
            name='message_by_sms',
            field=models.BooleanField(default=True, verbose_name='By SMS'),
        ),
        migrations.AddField(
            model_name='candidatecontact',
            name='recruitment_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_contacts', to='core.CompanyContact', verbose_name='Recruitment agent'),
        ),
    ]
