# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-20 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidatecontact_message_by_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecontact',
            name='loyalty_score',
        ),
        migrations.RemoveField(
            model_name='candidatecontact',
            name='reliability_score',
        ),
        migrations.RemoveField(
            model_name='candidatecontact',
            name='total_score',
        ),
    ]
