# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_removed_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillraterel',
            name='hourly_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_skill_rates', to='skills.SkillBaseRate', verbose_name='Hourly Rate'),
        ),
    ]
