# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-11 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_make_fk_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterel',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_rels', to='core.CompanyContact', verbose_name='Company Contact'),
        ),
    ]
