# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_skill_rel_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillrel',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Skill Rate'),
            preserve_default=False,
        ),
    ]
