# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_skillrel_default_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterel',
            name='master_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rels', to='core.Company', verbose_name='Master Company'),
        ),
    ]
