# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-25 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_skillrel_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillrel',
            name='active',
        ),
    ]
