# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-27 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0009_auto_20180625_1759'),
        ('candidate', '0010_remove_skillrel_active'),
    ]

    operations = [
    ]
