# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-18 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0012_removed_candidate_skill_rate_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterel',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='Is woner'),
        ),
    ]
