# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-18 13:21
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings

from r3sourcer.apps.core.models import Company


def migrate_candidate_default_rel(apps, schema_editor):
    CandidateContact = apps.get_model('candidate', 'CandidateContact')
    CandidateRel = apps.get_model('candidate', 'CandidateRel')
    Site = apps.get_model('sites', 'Site')

    site = Site.objects.filter(id=settings.SITE_ID).first()

    if site:
        site_company = site.site_companies.filter(company__type=Company.COMPANY_TYPES.master).first()
        company = site_company and site_company.company

        for candidate in CandidateContact.objects.filter(candidate_rels__isnull=True):
            CandidateRel.objects.get_or_create(
                candidate_contact=candidate,
                master_company=company,
                defaults={'owner': True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0013_candidaterel_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_candidate_default_rel, migrations.RunPython.noop)
    ]
