# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0015_candidatecontact_profile_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateContactAnonymous',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('candidate.candidatecontact',),
        ),
        migrations.AddField(
            model_name='candidaterel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
