# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-25 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0016_auto_20180723_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractorCandidateRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('candidate_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_candidates', to='candidate.CandidateContact', verbose_name='Candidate Contact')),
                ('subcontractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_candidates', to='candidate.Subcontractor', verbose_name='Subcontractor')),
            ],
            options={
                'verbose_name': 'Subcontractor Candidate Relation',
                'verbose_name_plural': 'Subcontractor Candidate Relations',
            },
        ),
    ]
