# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-07-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0017_subcontractorcandidaterelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='business_id',
            field=models.CharField(default=None, max_length=31, verbose_name='Business Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcontractor',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='core.Company'),
        ),
    ]
