# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-01 11:56
from __future__ import unicode_literals

from django.db import migrations


def migrate_candidate_superannuation(apps, schema_editor):
    CandidateContact = apps.get_model('candidate', 'CandidateContact')
    SuperannuationFund = apps.get_model('candidate', 'SuperannuationFund')

    for candidate in CandidateContact.objects.all():
        if not candidate.superannuation_fund:
            superannuation_fund = SuperannuationFund.objects.create(
                name=candidate.super_annual_fund_name, membership_number=candidate.super_member_number
            )
            candidate.superannuation_fund = superannuation_fund
            candidate.save(update_fields=['superannuation_fund'])
        else:
            superannuation_fund = candidate.superannuation_fund

            if not superannuation_fund.name:
                superannuation_fund.name = candidate.super_annual_fund_name

            if not superannuation_fund.membership_number:
                superannuation_fund.membership_number = candidate.super_member_number

            superannuation_fund.save()


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0018_subcontractor_business_id'),
    ]

    operations = [
        migrations.RunPython(migrate_candidate_superannuation, migrations.RunPython.noop)
    ]
