# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-08-01 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0019_migrate_superannuation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatecontact',
            name='super_annual_fund_name',
        ),
        migrations.RemoveField(
            model_name='candidatecontact',
            name='super_member_number',
        ),
    ]
