# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0020_removed_legacy_superannuation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superannuationfund',
            name='membership_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employee Membership Number'),
        ),
    ]
