# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0021_change_superannuationfund_number_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterel',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rels', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
        migrations.AlterField(
            model_name='candidaterel',
            name='company_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_rels', to='core.CompanyContact', verbose_name='Company Contact'),
        ),
        migrations.AlterField(
            model_name='acceptancetestrel',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_acceptance_tests', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
        migrations.AlterField(
            model_name='skillrel',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='candidate.CandidateContact'),
        ),
        migrations.AlterField(
            model_name='tagrel',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_rels', to='candidate.CandidateContact', verbose_name='Candidate Contact'),
        ),
    ]
