# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0022_change_on_delete_candidate_rel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SuperannuationFund',
            new_name='SuperannuationFundCandidate',
        ),
    ]
