# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0024_add_superannuation_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatecontact',
            old_name='superannuation_fund_rel',
            new_name='superannuation_fund',
        ),
        migrations.AlterUniqueTogether(
            name='superannuationfund',
            unique_together=set([('product_name', 'abn', 'usi')]),
        ),
    ]
