# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0025_rename_candidate_superfund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superannuationfund',
            old_name='name',
            new_name='fund_name',
        ),
    ]
