# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_pricelist_rate_modifier'),
        ('candidate', '0026_rename_super_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRateCoefficientRel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rate_coefficient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_coefficient_rels', to='pricing.RateCoefficient', verbose_name='Rate coefficient')),
                ('rate_coefficient_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_coefficient_rels', to='pricing.RateCoefficientModifier', verbose_name='Rate coefficient modifier')),
                ('skill_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skill_coefficient_rels', to='candidate.SkillRel', verbose_name='Candidate skill')),
            ],
            options={
                'verbose_name': 'Candidate Skill Rate Coefficient Relation',
                'verbose_name_plural': 'Candidate Skill Rate Coefficient Relations',
            },
        ),
        migrations.AlterField(
            model_name='candidaterel',
            name='owner',
            field=models.BooleanField(default=False, verbose_name='Is owner'),
        ),
        migrations.AlterUniqueTogether(
            name='skillratecoefficientrel',
            unique_together=set([('skill_rel', 'rate_coefficient', 'rate_coefficient_modifier')]),
        ),
    ]
