# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0028_change_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcontractor',
            options={'verbose_name': 'Subcontractor', 'verbose_name_plural': 'Subcontractors'},
        ),
        migrations.AlterField(
            model_name='acceptancetestquestionrel',
            name='question_answered_at',
            field=models.DateTimeField(verbose_name='Question Answered at'),
        ),
        migrations.AlterField(
            model_name='acceptancetestrel',
            name='test_finished_at',
            field=models.DateTimeField(verbose_name='Test Finished at'),
        ),
        migrations.AlterField(
            model_name='acceptancetestrel',
            name='test_started_at',
            field=models.DateTimeField(verbose_name='Test Started at'),
        ),
    ]
