# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-21 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20200321_1807'),
        ('candidate', '0030_auto_20191212_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateContactLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Company language',
                'verbose_name_plural': 'Company languages',
            },
        ),
        migrations.RemoveField(
            model_name='candidatecontact',
            name='language',
        ),
        migrations.AddField(
            model_name='candidatecontactlanguage',
            name='candidate_contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='candidate.CandidateContact', verbose_name='Candidate Contact language'),
        ),
        migrations.AddField(
            model_name='candidatecontactlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_contacts', to='core.Language', verbose_name='Language'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatecontactlanguage',
            unique_together=set([('candidate_contact', 'language')]),
        ),
    ]
