# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-15 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0032_auto_20200416_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecontact',
            name='recruitment_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_contacts', to='core.CompanyContact', verbose_name='Recruitment agent'),
        ),
    ]
