# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-11 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0033_auto_20200515_1744'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidatecontactlanguage',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='candidatecontactlanguage',
            name='candidate_contact',
        ),
        migrations.RemoveField(
            model_name='candidatecontactlanguage',
            name='language',
        ),
        migrations.DeleteModel(
            name='CandidateContactLanguage',
        ),
    ]
