# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-11-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0036_auto_20201103_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxnumbertype',
            name='max_length',
        ),
        migrations.AddField(
            model_name='taxnumbertype',
            name='regex_validation_pattern',
            field=models.CharField(default='\\d{9}', max_length=64, verbose_name='Tax Number Regex Validation Pattern'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxnumber',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
