# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-14 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0039_auto_20201109_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalid',
            name='candidate_contact',
        ),
        migrations.RemoveField(
            model_name='personalid',
            name='type',
        ),
        migrations.RemoveField(
            model_name='personalidtype',
            name='country',
        ),
        migrations.RemoveField(
            model_name='taxnumber',
            name='candidate_contact',
        ),
        migrations.RemoveField(
            model_name='taxnumber',
            name='type',
        ),
        migrations.RemoveField(
            model_name='taxnumbertype',
            name='country',
        ),
        migrations.DeleteModel(
            name='PersonalID',
        ),
        migrations.DeleteModel(
            name='PersonalIDType',
        ),
        migrations.DeleteModel(
            name='TaxNumber',
        ),
    ]
