# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-20 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0040_auto_20201214_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxNumberType',
        ),
    ]
