# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-28 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_formlanguage_model'),
        ('candidate', '0041_delete_taxnumbertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tax_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tax Number')),
                ('personal_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Personal ID')),
                ('candidate_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.CandidateContact', verbose_name='Contact')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formalities', to='core.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Formality',
                'verbose_name_plural': 'Formalities',
            },
        ),
    ]
