# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20210109_1110'),
        ('candidate', '0044_auto_20210105_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillrel',
            old_name='hourly_rate',
            new_name='rate',
        ),
        migrations.AddField(
            model_name='skillrel',
            name='uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UnitOfMeasurement', verbose_name='Unit of measurement'),
        ),
    ]
