# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0044_auto_20210105_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterel',
            name='sharing_data_consent',
            field=models.BooleanField(default=False, verbose_name='Candidate Consent'),
        ),
    ]
