# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-23 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_candidaterel_sharing_data_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrel',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Skill Rate'),
        ),
    ]
