# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0045_add_SkillRate_model'),
        ('candidate', '0045_candidaterel_sharing_data_consent'),
    ]

    operations = [
    ]
