# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-10 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    def move_rates_to_skillrate(apps, schema_editor):
        SkillRel = apps.get_model("candidate", "SkillRel")
        SkillRate = apps.get_model("candidate", "SkillRate")
        WorkType = apps.get_model("skills", "WorkType")

        for skill_rel in SkillRel.objects.all():
            if skill_rel.hourly_rate:
                hourly_work = WorkType.objects.filter(name='Hourly work',
                                                      skill_name=skill_rel.skill.name) \
                                              .first()
                SkillRate.objects.create(skill_rel=skill_rel,
                                         worktype=hourly_work,
                                         rate=skill_rel.hourly_rate)


    dependencies = [
        ('skills', '0032_auto_20210520_1010'),
        ('candidate', '0047_auto_20210520_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Skill Rate')),
            ],
            options={
                'verbose_name': 'Skill rate',
                'verbose_name_plural': 'Skill rates',
            },
        ),
        migrations.AddField(
            model_name='skillrate',
            name='skill_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rates', to='candidate.SkillRel', verbose_name='Candidate Skill'),
        ),
        migrations.AddField(
            model_name='skillrate',
            name='worktype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_rates', to='skills.WorkType', verbose_name='Type of work'),
        ),
        migrations.AlterUniqueTogether(
            name='skillrate',
            unique_together=set([('skill_rel', 'worktype')]),
        ),

        migrations.RunPython(move_rates_to_skillrate),

        migrations.RemoveField(
            model_name='skillrel',
            name='hourly_rate',
        ),
    ]
