# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0048_auto_20210610_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillrate',
            name='worktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_rates', to='skills.WorkType', verbose_name='Type of work'),
        ),
    ]
