# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-11-17 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0049_auto_20210626_1002'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidatecontact',
            managers=[
                ('filtered_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='skillratecoefficientrel',
            name='rate_coefficient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_skill_coefficient_rels', to='pricing.RateCoefficient', verbose_name='Rate coefficient'),
        ),
        migrations.AlterField(
            model_name='skillratecoefficientrel',
            name='rate_coefficient_modifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_skill_coefficient_rels', to='pricing.RateCoefficientModifier', verbose_name='Rate coefficient modifier'),
        ),
    ]
