# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-12-13 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0050_auto_20211117_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_contacts', to='core.Contact', verbose_name='Contact'),
        ),
    ]
