FROM python:3.5.7

WORKDIR /app/
ADD dependencies ./dependencies
ADD helpers ./helpers
ADD ["docker-entrypoint.sh", "Procfile", "README.md", "setup.py", "pytest.ini", ".coveragerc", "./"]
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get install -y nodejs
RUN npm i -g bower
RUN mkdir -p r3sourcer var/log var/run var/www var/tmp
RUN pip install virtualenv
RUN virtualenv -p python3.5 venv/py3 && ln -s venv/py3/bin bin
RUN bin/pip install -r dependencies/pip_pytest.txt

# available only uwsgi port
EXPOSE 8081
