FROM python:3.5.2
ARG VENV_ROOT
ARG BASE_DIR
ARG PRIVATE_REPO_KEY
ARG EXPOSE_PORT

RUN mkdir /root/.ssh/
ADD ${PRIVATE_REPO_KEY} /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN ssh-keyscan -T 60 bitbucket.org >> /root/.ssh/known_hosts

WORKDIR ${BASE_DIR}
ADD dependencies ./dependencies
ADD helpers ./helpers
ADD ["docker-entrypoint.sh", "Procfile", "README.md", "setup.py", "./"]
RUN apt-get update && apt-get install -y nodejs-legacy npm
RUN npm i -g bower
RUN mkdir -p r3sourcer var/log var/run var/www var/tmp
RUN pip install virtualenv
RUN virtualenv ${VENV_ROOT}/py3 -p /usr/local/bin/python3.5 && virtualenv ${VENV_ROOT}/py2 -p /usr/bin/python2.7
RUN ln -s venv/py3/bin bin
RUN venv/py2/bin/pip install six
RUN bin/pip install six
RUN bin/pip install --process-dependency-links -r dependencies/pip_py3.txt && bin/pip install -e . && venv/py2/bin/pip install -r dependencies/pip_py2.txt
RUN bin/pip install --no-cache-dir --process-dependency-links `cat dependencies/submodules.txt`

# available only uwsgi port
EXPOSE ${EXPOSE_PORT}

ENTRYPOINT ["./docker-entrypoint.sh"]
