# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import r3sourcer.apps.twilio.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms_interface', '0001_initial'),
        ('core', '0002_auto_20171102_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('sid', models.CharField(editable=False, help_text='Twilio account SID', max_length=256, unique=True, verbose_name='SID')),
                ('owner_account_sid', models.CharField(blank=True, default='', max_length=256, verbose_name='Owner account SID')),
                ('account_type', models.CharField(default='Full', editable=False, max_length=16, verbose_name='Type')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16, verbose_name='Status')),
                ('friendly_name', models.CharField(default='', editable=False, max_length=512, verbose_name='Friendly name')),
                ('last_sync', models.DateField(default=None, editable=False, null=True, verbose_name='Last sync account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('reply_timeout', models.IntegerField(default=4, help_text='Minutes', verbose_name='Reply timeout')),
                ('delivery_timeout', models.IntegerField(default=4, help_text='Minutes', verbose_name='Delivery timeout')),
                ('sid', models.CharField(max_length=256, verbose_name='Twilio account id')),
                ('auth_token', models.CharField(max_length=256, verbose_name='Twilio auth token')),
                ('last_sync', models.DateTimeField(default=None, null=True, verbose_name='Last sync')),
                ('parse_from_date', models.DateField(default=r3sourcer.apps.twilio.models.get_parse_date_from, verbose_name='Parse from date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twilio_credentials', to='core.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Twilio credentials',
                'verbose_name_plural': 'Twilio credentials',
            },
        ),
        migrations.CreateModel(
            name='TwilioPhoneNumber',
            fields=[
                ('phonenumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sms_interface.PhoneNumber')),
                ('account_sid', models.CharField(editable=False, max_length=128, verbose_name='Account SID')),
            ],
            options={
                'verbose_name': 'Twilio phone number',
                'verbose_name_plural': 'Twilio phone numbers',
            },
            bases=('sms_interface.phonenumber',),
        ),
        migrations.CreateModel(
            name='TwilioSMSMessage',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('sms_interface.smsmessage',),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_list', to='twilio.TwilioCredential', verbose_name='Credentials'),
        ),
        migrations.AddField(
            model_name='twilioaccount',
            name='phone_numbers',
            field=models.ManyToManyField(related_name='twilio_accounts', to='twilio.TwilioPhoneNumber', verbose_name='Phone numbers'),
        ),
    ]
